/**
 * Content for the Stardust & Beyond site - a 1970s disco photo archive.
 * Generated from source/Stardust and Beyond.docx by the one-off importer.
 * Each gallery item is { file, title? } - `title` is the photo caption.
 * Array order = display order.
 */

export const SITE = {
  name: "Stardust & Beyond",
  role: "A 1970s disco, and the friends who lived it",
  url: "https://stardustandbeyond.com",
};

export const SOCIAL = {
  instagram: "",
  bluesky: "",
  whatsapp: "https://chat.whatsapp.com/FGV5V4qmuPYJjy2lxdZZcV?s=sw&p=a&mlu=4",
};

// The club photo that leads the site (first uncaptioned image in The Stardust).
export const LEAD = { kind: "the-stardust", file: "image861" };

// Section registry - drives the nav, the home "rooms" grid, and page builders.
export const SECTIONS = [
  { kind: "the-stardust", label: "The Stardust", href: "the-stardust.html", unit: "photos", blurb: "The club, 1975." },
  { kind: "the-boudoir", label: "The Boudoir", href: "the-boudoir.html", unit: "photos", blurb: "Steven's bedroom, and The Onion Ring." },
  { kind: "steven", label: "Steven", href: "steven.html", unit: "photos", blurb: "Steven Roche, aka Margot." },
  { kind: "70s", label: "70’s", href: "70s.html", unit: "photos", blurb: "The decade it all began." },
  { kind: "80s", label: "80’s", href: "80s.html", unit: "photos", blurb: "Bigger, brighter, bolder." },
  { kind: "90s", label: "90’s", href: "90s.html", unit: "photos", blurb: "The friends, years on." },
  { kind: "2000", label: "2000", href: "2000.html", unit: "photos", blurb: "Into the new century." },
];

export const STARDUST_TEXT = [
  "The Stardust was the only Gay club in Durban. It was a secret and only gay people and their friends knew about it. There was no sign on the anonymous door and you had to climb to the 3rd floor of a building down a dark alleyway between 2 of the main roads right in the centre of the city. Joan Dickman and I were taken there by Hilton Wolman in early January 1975. It was a small nightclub with a tiny dance floor and a bar. This was a completely new, scary and shocking world to us. I introduced the club to Patrick, Rory and Cindy and we had so much fun on the dancefloor that we began going regularly. We felt truly liberated there. In April Joan and I went to our first drag competition. Miss Natal 1975. The club was jam packed filled with screaming supporters of all these beautiful “girls”. We had never seen anything like it before. Joan suddenly realised that the queen who came third was in her maths class at university. The following Monday in the maths class she leant forward, tapped him on the shoulder and said “You looked fabulous on Friday night”. So began our friendship with Steven. From that moment onwards our lives would never be the same again.",
];

export const BOUDOIR_TEXT = [
  "The boudoir was the name given to Steven Roche’s bedroom. It was an annex at the back of the Roche family home where a group of very close knit friends used to congregate and hang out all the time. This group was eventually nicknamed The Onion Ring. We used to turn up at the Roche home where the doors were always open and walk through the house greeting other members of the family until we got to Steven’s boudoir where we would spend hours sitting around chatting and drinking endless cups of tea. Occasionally these gatherings would turn into little parties with hysterical laughter and lots of fun and games."
];

export const THE_STARDUST = [
  { file: "image446", title: "Steven Roche aka Margot" },
  { file: "image694", title: "Alan Horn, Patrick Brill and Cindy West" },
  { file: "image267", title: "Cindy West" },
  { file: "image813" },
  { file: "image818", title: "An invitation to the Miss Sunshine at The Butterworth Hotel in Durban" },
  { file: "image900", title: "Rodney Symes, Eric Reeves, Carol and Barry. Eric and Barry were the owners of The Stardust." },
  { file: "image674", title: "Steven at Rocky Horror party" },
  { file: "image692" },
  { file: "image748", title: "Miss Stardust 1977" },
  { file: "image162", title: "Lesley Wallace" },
  { file: "image297", title: "Steven and Gary" },
  { file: "image886", title: "Gary" },
  { file: "image452", title: "Steven doing cabaret at The Stardust" },
  { file: "image504", title: "Darryl Rogers" },
  { file: "image533", title: "Darryl and Gillian" },
  { file: "image488", title: "Henry Davies and Darryl" },
  { file: "image377", title: "Joan Dickman and Pam Harmse" },
  { file: "image491", title: "Darryl, Kevin Rogers and Gillian Lenton" },
  { file: "image167", title: "Dickie Conradie" },
  { file: "image117", title: "Rene Kent" },
  { file: "image437", title: "Sophie Symes" },
  { file: "image390", title: "Gavin Woolf aka The Weep" },
  { file: "image700", title: "Steven and Craig Peetz" },
  { file: "image794", title: "Steven crowning Miss Stardust 1977" },
  { file: "image415", title: "Steven, Craig, Ronnie Botha, Henry and Mark Griffin" },
  { file: "image313", title: "Henry and Lauren Shipton" },
  { file: "image676", title: "Lauren and Ian Perry" },
  { file: "image73", title: "Craig as Miss Natal 1977" },
  { file: "image201", title: "Kerry Bennett at The Stardust" },
  { file: "image782", title: "Lauren" },
  { file: "image797", title: "Ian Perry winning Miss South Africa" },
  { file: "image445", title: "Miss South Africa Lesley Wallace, Ian Perry, Steven Roche, Gillian and Peter Wheeler The Stardust DJ." },
  { file: "image551" },
  { file: "image734", title: "Steven doing Martie the Martian" },
  { file: "image507", title: "Lauren" },
  { file: "image479", title: "Marcel Wishura" },
  { file: "image224", title: "Ian and Peter Pienaar, the owner of the Stardust" },
];

export const THE_BOUDOIR = [
  { file: "image600", title: "Keith, Trevor Norris, Mark Griffin and Henry Davies" },
  { file: "image666", title: "Steven, Keith, Trevor, Henry, Mark, Michael Hunter Smith, Elaine Welsh, Jackie Bryant, Rodney Symes, Patrick Brill, Steven Kent and Karen Ward" },
  { file: "image100", title: "Patrick, Rene and Rodney" },
  { file: "image251", title: "Steven" },
  { file: "image366", title: "Jackie, Mark & Steven" },
  { file: "image573", title: "Sally Fisher and Steven" },
  { file: "image104", title: "Steven dressed up to crown Miss Stardust 1977" },
  { file: "image333", title: "Henry sewing Steven's dress" },
  { file: "image99", title: "Joan, Margaret Mott Adams, Steven and Patrick at Steven's birthday party in the Boudoir." },
  { file: "image158", title: "Henry at Steven's birthday party" },
  { file: "image279", title: "Jackie, Henry, Pam, Steven and Conrad" },
  { file: "image90", title: "Jackie, Mrs Roche and Steven aka Rene" },
  { file: "image744", title: "Richard Rufus Ellis and Steven" },
  { file: "image628", title: "Outside the Boudoir. Rene, Jackie, Mark, Gillian and Steven" },
  { file: "image243", title: "Steven and Mark" },
  { file: "image882", title: "Thelma, Mr Roche and Gillian" },
  { file: "image584", title: "Gillian" },
  { file: "image339", title: "Gillian" },
  { file: "image414", title: "Keith and Steven" },
  { file: "image354", title: "Henry" },
  { file: "image753", title: "Gavin, Illana Woolf and Henry" },
  { file: "image425", title: "Steven and Henry" },
];

export const STEVEN = [
  { file: "image826", title: "Steven" },
  { file: "image877", title: "Steven" },
  { file: "image209", title: "Steven and Jackie" },
  { file: "image422", title: "Steven and Mark" },
  { file: "image851", title: "Steven and Adi" },
  { file: "image554", title: "Steven and Mark" },
  { file: "image264", title: "Steven modelling in Overport City photographed by his father" },
  { file: "image636" },
  { file: "image413" },
  { file: "image490" },
  { file: "image713", title: "Peter Moffat and Steven" },
  { file: "image739", title: "Steven in his back garden" },
  { file: "image508", title: "Steven and Rene- The Eclair Sisters" },
  { file: "image911", title: "Steven and Rene" },
  { file: "image475", title: "Adi and Steven" },
  { file: "image448", title: "Steven as Margot" },
  { file: "image386", title: "Steven and Gary" },
  { file: "image821", title: "Trevor and Steven" },
  { file: "image505", title: "The Eclair Sisters- Trish and Trash Eclair" },
  { file: "image641", title: "Steven" },
  { file: "image463", title: "The Eclair Sisters" },
  { file: "image464", title: "Steven and Jackie's travels in Europe" },
  { file: "image402", title: "Steven" },
  { file: "image24" },
  { file: "image271", title: "Steven doing cabaret in Johannesburg" },
  { file: "image376", title: "Steven and The Spice Girls" },
  { file: "image850", title: "Steven's collage" },
  { file: "image420", title: "Steven's collage" },
  { file: "image139", title: "Steven doing cabaret" },
];

export const SEVENTIES = [
  { file: "image733", title: "Henry and Cindy shopping in Durban" },
  { file: "image235", title: "Cindy in Johannesburg" },
  { file: "image852", title: "Cindy" },
  { file: "image814", title: "Cindy and Marcel Wishura" },
  { file: "image595", title: "Henry at The Linger Longer restaurant in Johannesburg" },
  { file: "image639", title: "Richard Lawton" },
  { file: "image572", title: "Trevor, Anick his sister and Michael" },
  { file: "image492", title: "Michael and Elaine" },
  { file: "image549", title: "Trevor and Michael" },
  { file: "image856", title: "Patrick and Kerry in Raffles, The Maharani Hotel, Durban" },
  { file: "image768", title: "Patrick, Kerry and Mario Rodrigues at Raffles in The Maharani Hotel Durban" },
  { file: "image637", title: "Lawrence Potgieter and Cindy in The Hoffman New Yorker, Hillbrow, Johannesburg" },
  { file: "image663" },
  { file: "image227", title: "Illana and Henry at Jan Smuts airport to see Cindy leave for London" },
  { file: "image323", title: "Henry" },
  { file: "image10", title: "Cindy and Henry" },
  { file: "image49", title: "Ronnie Botha at Marchpane Terraces" },
  { file: "image566", title: "Anthony, Cindy, Patrick and Henry at Marchpane Terraces, Yeoville, Johannesburg" },
  { file: "image765", title: "Henry and Cindy at Marchpane Terraces, Yeoville, Johannesburg" },
  { file: "image230", title: "Cindy messing around in The Landrost Hotel, Johannesburg" },
  { file: "image298" },
  { file: "image703", title: "Henry in the army at Bourkes Luck" },
  { file: "image500", title: "Henry in the army at The Potholes, Bourkes Luck" },
  { file: "image152", title: "Henry in the army" },
  { file: "image743" },
  { file: "image605", title: "Rory West and Patrick as trainee chefs at The Elangeni Hotel, Durban" },
  { file: "image12", title: "Medieval Party. Heather, Jackie, Gillian, Steven, Trevor and Rene" },
  { file: "image119", title: "Steven and Gillian" },
  { file: "image7", title: "Steven, Rene and Gillian" },
  { file: "image404", title: "and Trevor" },
  { file: "image635", title: "Trevor" },
  { file: "image113", title: "Trevor" },
  { file: "image61", title: "Steven, Richard and Rene" },
  { file: "image228", title: "Michael and Trevor" },
  { file: "image395" },
  { file: "image461", title: "Michael, Lindi and Trevor" },
  { file: "image647", title: "Michael" },
  { file: "image194", title: "Trevor and Sally" },
  { file: "image510", title: "Sally, Steven and Richard" },
  { file: "image868", title: "Sally and Karen" },
  { file: "image196", title: "Trevor" },
  { file: "image359", title: "Trevor and Charlie Brown" },
  { file: "image696", title: "Steven" },
  { file: "image86", title: "Karen" },
  { file: "image817", title: "Thelma and Tony" },
  { file: "image832", title: "Michael, Trevor and Steven" },
  { file: "image709", title: "Steven" },
  { file: "image575", title: "Illana" },
  { file: "image831", title: "Rene" },
  { file: "image574", title: "Lauren got shot" },
  { file: "image352", title: "Patrick and Wally Hayward at the Star Wars party at The Zodiac" },
  { file: "image204", title: "Kerry and Wally" },
  { file: "image332", title: "Louis de Araujo" },
  { file: "image424", title: "Rory's 21st birthday, London" },
  { file: "image789", title: "Henry and Chin Soon at Rory's 21st birthday" },
  { file: "image218", title: "Susie and Henry" },
  { file: "image124", title: "The Leopard and Cindy" },
  { file: "image288", title: "Rory, London" },
  { file: "image263", title: "Darryl" },
  { file: "image202", title: "Kerry Bennett modelling The Walsh Marais Gallery kaftan" },
  { file: "image578", title: "Henry working at Thats It, Hillbrow, Johannesburg" },
  { file: "image836", title: "Henry" },
  { file: "image133", title: "Hofman New Yorker envelope" },
  { file: "image212", title: "Lauren and Rocky Farren" },
  { file: "image752", title: "The Leopard, Rory and Henry" },
  { file: "image803" },
  { file: "image231", title: "Darryl" },
  { file: "image180", title: "Rory and Henry, London" },
  { file: "image802" },
  { file: "image580", title: "Simone and Darryl in Ronnie Botha's flat" },
  { file: "image206", title: "Henry hanging out at Ronnie Botha's flat" },
  { file: "image173", title: "Darryl" },
  { file: "image284", title: "Steven and Jackie" },
  { file: "image144", title: "Steven, Alwyn, Arthur and Jackie in Mykonos" },
  { file: "image556", title: "Rory" },
  { file: "image552", title: "Cindy" },
  { file: "image747", title: "Louis, Illana and Michael van Rensburg at Jan Smuts airport for Rory's flight to London" },
  { file: "image34", title: "Rory, Illana and Henry at Jan Smuts airport for Rory's farewell to London" },
  { file: "image406", title: "Lauren" },
  { file: "image730", title: "Janet Marchpane" },
  { file: "image816", title: "Cindy" },
  { file: "image161", title: "Cindy and Henry" },
  { file: "image880", title: "Louis Christmas Card 1978" },
  { file: "image702", title: "Rory getting ready for New Years Eve party London" },
  { file: "image691", title: "Cindy and Rory" },
  { file: "image123", title: "Rory and Cindy" },
  { file: "image536", title: "Louis' brilliant cartoon" },
  { file: "image193", title: "Louis and Illana seeing Rory off to London" },
  { file: "image150", title: "Marcel Wishura" },
  { file: "image829", title: "Rory in the army In Potschefstroom" },
  { file: "image522", title: "Louis's Christmas Card" },
  { file: "image391", title: "Rene as Miss Subway" },
  { file: "image319", title: "Neil Starr" },
  { file: "image777", title: "Mathew Kelly" },
  { file: "image443", title: "Spencer Pillay and Rene" },
  { file: "image620", title: "Noel van Wildenrath and Henry" },
  { file: "image324", title: "Noel van Wildenrath" },
  { file: "image599", title: "Peter Moffat aka Petal" },
  { file: "image456", title: "Louis' Cartoon" },
  { file: "image862", title: "Darryl" },
  { file: "image812", title: "Steven in Greece" },
  { file: "image586", title: "Steven" },
  { file: "image154", title: "Kerry" },
  { file: "image307", title: "Janet Doby and Patrick" },
  { file: "image375", title: "Patrick and Kerry" },
  { file: "image254", title: "Durban Tech" },
  { file: "image114", title: "Cindy on holiday" },
  { file: "image53", title: "Cindy and Henry" },
  { file: "image458", title: "The Together Bar, Hillbrow, Johannesburg" },
  { file: "image793", title: "Albie, Stephen Pritchard, Wally Haywood, Bernard Hatch and Henry getting ready for a Rocky Horror party" },
  { file: "image904", title: "Cindy" },
  { file: "image89", title: "Lauren Shipton" },
  { file: "image711", title: "Henry in Paris" },
  { file: "image81", title: "Patrick at The Landdrost Hotel, Johannesburg" },
  { file: "image186", title: "Henry and Illana at her school dance" },
  { file: "image908", title: "Patrick at Chelsea Studios, Chelsea, London" },
  { file: "image608", title: "Henry in London" },
  { file: "image75", title: "Henri and Patrick at he Cinzano Design Competition" },
  { file: "image833", title: "Cheryl Johnson, Sharon Coetsee, Louis, Henry, Stephen and Kerry" },
];

export const EIGHTIES = [
  { file: "image371", title: "Henri, Alan Morrison" },
  { file: "image465", title: "David Goudge" },
  { file: "image255", title: "David, Kerry, Patrick and Henri" },
  { file: "image153", title: "Kevin Botha, Graham Moore, Steven and Peter Moffat" },
  { file: "image901", title: "Cheryl Johnson, David Davies and Henri modelling Andrew Verster's costumes for A Midsummer Night's Dream" },
  { file: "image141", title: "Rehearsal for a show. Steven Lawrences, Dale Shultz, Gary Halfpenny, Kerry, Henri, Gail Butler and Laurel" },
  { file: "image334", title: "Henri Davies" },
  { file: "image470", title: "Lauren and Steven in LA" },
  { file: "image645", title: "Steven in LA" },
  { file: "image331", title: "Steven and Chi Chi La Rue in LA" },
  { file: "image499", title: "Steven in LA" },
  { file: "image19", title: "Lauren and Tom Collins" },
  { file: "image502", title: "Patrick and Henri at Houghton Mansions, Johannesburg" },
  { file: "image487", title: "Louis, Henri and Sophie" },
  { file: "image430", title: "Garth weekend down the South Coast" },
  { file: "image412", title: "Stephen down the South Coast" },
  { file: "image343", title: "Stephen" },
  { file: "image468", title: "Garth" },
  { file: "image482", title: "Mark, Steven and Tom. A weekend at Granny's Cottage, Ballito Bay" },
  { file: "image266", title: "Patrick, Tom, Rene, Steven, Ian Mark & Garth" },
  { file: "image796", title: "Henri, Richard, Ian, Rene, Steven and Ricky" },
  { file: "image659", title: "Ian, Steven, Ricky, Richard, Rene & Henri" },
  { file: "image905", title: "Rene" },
  { file: "image309", title: "Steven and Rene" },
  { file: "image688", title: "Rene" },
  { file: "image805", title: "Rene doing Miss Subway" },
  { file: "image786", title: "x and Rene" },
  { file: "image122", title: "Richard and Tom" },
  { file: "image854", title: "Ian, Richard, Steven and Patrick" },
  { file: "image792", title: "Steven aka The Pennay, Mark and Mathew at the GAZA Ball, Johannesburg" },
  { file: "image806", title: "x, Alan Froneman and Louis- GAZA Ball" },
  { file: "image763", title: "x and Mark" },
  { file: "image604", title: "Henri, The Pennay and Patrick at The Gasa Ball" },
  { file: "image867", title: "Alan aka Alice and Mathew" },
  { file: "image239", title: "Steven, Mark and Mathew" },
  { file: "image68", title: "Mark" },
  { file: "image70", title: "David" },
  { file: "image585", title: "David" },
  { file: "image652", title: "Garth" },
  { file: "image624", title: "Henri and Miguel at Karen Hollister's 21st Birthday" },
  { file: "image583", title: "Rene and Henri" },
  { file: "image762", title: "Alfie Saville and Henri at HD Menswear store, Salisbury Arcade, Durban" },
  { file: "image567", title: "Mirco Broggian at HD Menswear" },
  { file: "image588", title: "Garth and Tamar Marqaud" },
  { file: "image295", title: "Henri, Lianne Basson, Marcel Wishura and Linda Basson. A weekend in the Berg" },
  { file: "image360", title: "Patrick, Henri, Linda and Marcel" },
  { file: "image171", title: "Adele Shandel" },
  { file: "image17", title: "Kerry Bennett Fashion Show Liz Staniford, Cheryl Johhnson & Kerry Bennett" },
  { file: "image157", title: "David Goudge" },
  { file: "image684", title: "A day at Salt Rock Beach Steven and Ian" },
  { file: "image462", title: "Patrick" },
  { file: "image775", title: "Henri and Rene" },
  { file: "image18", title: "Duncan and Liz Good" },
  { file: "image612", title: "Ian, Henri and Patrick" },
  { file: "image355", title: "Rene" },
  { file: "image276", title: "Patrick in Cape Town" },
  { file: "image15", title: "Murray Scannell and Patrick" },
  { file: "image419", title: "Cape Town drag party Lynton Lefevre, Patrick and Maxi Spazzoli" },
  { file: "image198", title: "Lynton and Patrick" },
  { file: "image78", title: "A weekend down the South Coast Mark Dingley, Henri, Wayne Kobusch and Noel Osborne" },
  { file: "image675", title: "Cape Town road trip Henri, Gary Halfpenny and Mark" },
  { file: "image629", title: "Mark, Gary and Henri" },
  { file: "image129", title: "Medieval Dinner Party, Albion Road, Rondebosch, Cape Town Patrick, Maxi and Henri" },
  { file: "image560", title: "Stephen Doubell and Maxi" },
  { file: "image278", title: "Murray, Jeneanne, Henri, Ian Swan, Maxi, Patrick and Myra" },
  { file: "image125" },
  { file: "image678", title: "Patrick, Janet Dobey, Henry , Myra Cowell and Murray" },
  { file: "image174", title: "Adele's 21st birthday, Cape Town. Stephen, Adele, Henri, Carolyn and Patrick" },
  { file: "image656", title: "Jenny Bear, Carolyn, Marcel and Adele" },
  { file: "image740", title: "Lauren" },
  { file: "image496", title: "Cheryl Schultz" },
  { file: "image778", title: "Cheryl in Miss Scope, Sun City" },
  { file: "image328", title: "Cheryl and Patrick in Le Chic, Durban" },
  { file: "image118", title: "Garth and Patrick" },
  { file: "image265", title: "Patrick, Cheryl and Henri" },
  { file: "image69", title: "David" },
  { file: "image481", title: "Patrick and Garth" },
  { file: "image669", title: "Gail Butler in Parrot fashion" },
  { file: "image36", title: "Parrot, Durban" },
  { file: "image613", title: "Henri and Bryan Brett at The Cinzano Design competition" },
  { file: "image495", title: "Rafe Brown and Albert Eloff at the Cinzano Design competition" },
  { file: "image145", title: "Lauren and Grace Jones" },
  { file: "image914", title: "Patrick, Kerry and Neville in Gillian's flat" },
  { file: "image57", title: "x, Spencer, Rene and Lauren" },
  { file: "image698", title: "Mark's birthday at Le Chic" },
  { file: "image526", title: "Karen Ward and Steven" },
  { file: "image244", title: "Patrick, Maxi, Kerry, x and Garth" },
  { file: "image888", title: "Kerry" },
  { file: "image790", title: "David, Kerry Patrick and Henri" },
  { file: "image222", title: "Lauren, Henri and Dale Schultz" },
  { file: "image409", title: "Dale, Henri and Lauren" },
  { file: "image207", title: "Lauren, Dale and Henri" },
  { file: "image657", title: "Henri" },
  { file: "image577", title: "Henri and Lauren" },
  { file: "image515", title: "Lauren, Henri and Dale" },
  { file: "image685", title: "Lauren and Henri" },
  { file: "image837", title: "Patrick" },
  { file: "image384", title: "Christmas at Ians. Ian" },
  { file: "image823", title: "Stephen" },
  { file: "image717", title: "Rene" },
  { file: "image523", title: "Gillian, Mark and Rene" },
  { file: "image197", title: "Steven" },
  { file: "image535", title: "Gillian and Stephen" },
  { file: "image459", title: "Garth" },
  { file: "image570", title: "Musgrave Mansions, Musgrave Road, Berea, Durban" },
  { file: "image214", title: "Henry at Musgrave Mansions" },
  { file: "image844", title: "Ronnyz" },
  { file: "image863", title: "Kerry, Henry, Maxi and Patrick" },
  { file: "image538", title: "Neville Ward's 50's party Henri, Barbara Lindsey, Kerry, Maxi and Patrick" },
  { file: "image50", title: "Alexander Manbsions, Essenwood Road, Berea, Durban" },
  { file: "image457", title: "Henri and Casper" },
  { file: "image887", title: "Henri's dining room with Casper at Alexander Mansions" },
  { file: "image643", title: "Henri's 30th birthday party, Alexander Mansions, Durban Leigh Downing, Henri, Rene and Kerry" },
  { file: "image236", title: "Steven, Henri and Mark" },
  { file: "image587", title: "Gary, Henri, Mark and Garth" },
  { file: "image325", title: "Peter, Glenda, Rene, Leigh and Steven" },
  { file: "image52", title: "330 Nightclub, Point Road, Durban" },
  { file: "image589", title: "Penny Rey, Sandra and Terry Scott" },
  { file: "image108", title: "Art Deco relaunch Elsa Pretorius, Eddy de Lima, Henri, Leigh, Cecil Sagorin and x" },
  { file: "image95", title: "LA" },
  { file: "image541", title: "Lauren, Jeffery Sanker and x" },
  { file: "image9", title: "x, Lauren and Steven, LA" },
  { file: "image825", title: "Henri's birthday dinner. Sally, Lauren and Steven" },
  { file: "image634", title: "Ian, Henri and Patrick" },
  { file: "image489" },
  { file: "image252", title: "Henri and Ian" },
  { file: "image830", title: "Lauren and Patrick" },
  { file: "image828", title: "Duncan and Liz Good's wedding" },
  { file: "image896", title: "Vetchies Pier, Durban Garth and Noel" },
  { file: "image166", title: "David and Bernard" },
  { file: "image320", title: "Jack's farewell drag party. Mark and Patrick" },
  { file: "image48", title: "Jack's farewell drag party. Jack, Bruce, Rene, Ian, Patrick, Steven and Mark" },
  { file: "image187", title: "Henri, Steven, Garth and Mark" },
  { file: "image726", title: "GASA Festival, Durban" },
  { file: "image455", title: "Durban Gay Festival, Frank Melman" },
  { file: "image653", title: "Durban Gay Festival" },
  { file: "image286", title: "GASA Festival" },
  { file: "image558", title: "Gay Students" },
  { file: "image569" },
  { file: "image512" },
  { file: "image834", title: "The judges. Ronnie Botha, Garth Gething" },
  { file: "image884", title: "Hunk compere Penelope Stevens aka Steven" },
  { file: "image316", title: "Steven and hunk" },
  { file: "image614", title: "Hunks" },
  { file: "image3", title: "Steven" },
  { file: "image374", title: "Hunks and Steven" },
  { file: "image128", title: "Hunk competition" },
  { file: "image799", title: "ID3 Fashion Show" },
  { file: "image281", title: "Mark Griffin, Rene" },
  { file: "image21", title: "Cabaret. Mark" },
  { file: "image503", title: "Cabaret" },
  { file: "image431", title: "Mark" },
  { file: "image91", title: "Cabaret. Mark" },
  { file: "image704", title: "Mark" },
  { file: "image460", title: "Mark" },
  { file: "image378", title: "Mark" },
  { file: "image399" },
  { file: "image111", title: "Yazoo staff" },
  { file: "image749", title: "Rene" },
  { file: "image725" },
  { file: "image250" },
  { file: "image808", title: "Peter" },
  { file: "image755", title: "Henri's fashion label launch" },
  { file: "image876", title: "Lauren, Sally and" },
  { file: "image630", title: "Lauren and Steven" },
  { file: "image326", title: "Michael, Trevor and Steven" },
  { file: "image23", title: "Michael, Trevor and Steven" },
  { file: "image516", title: "Steven, Rene, Mark" },
  { file: "image393", title: "Gillian wearing Henri Davies" },
  { file: "image682", title: "Gillian wearing Henri Davies" },
  { file: "image686", title: "Ian in the Glamorous Granny competition" },
  { file: "image40", title: "Peter White in Glamorous Granny" },
  { file: "image306", title: "Ian the winner of Glamorous Granny" },
  { file: "image247", title: "Michael" },
  { file: "image350", title: "Michael" },
  { file: "image348", title: "Cecil Lyons, Alan and Michael" },
  { file: "image701", title: "Michael" },
  { file: "image785", title: "SAA flying crew. Michael and Phillip Schaffer" },
  { file: "image232", title: "MIchael" },
  { file: "image562", title: "Michael" },
  { file: "image532" },
  { file: "image290", title: "Johan" },
  { file: "image35", title: "Steven, Neil and x" },
  { file: "image349", title: "Mark" },
  { file: "image699", title: "Michael at Blaauwbergstrand" },
  { file: "image687", title: "x, Neil Dundas and Steven" },
  { file: "image45", title: "Lauren and Ian" },
  { file: "image670", title: "Gillian, Lee Fine and Ian" },
  { file: "image727" },
  { file: "image721", title: "Spencer" },
  { file: "image389", title: "Rene" },
  { file: "image894", title: "x and Neil Starr" },
  { file: "image913", title: "Mark" },
  { file: "image611", title: "Rene" },
  { file: "image181", title: "Mark" },
  { file: "image784", title: "Mark" },
  { file: "image615", title: "Mark" },
  { file: "image864", title: "Mark" },
  { file: "image11", title: "Lauren and Tom Collins" },
  { file: "image423", title: "Michael" },
  { file: "image155", title: "Seaton and Leonardo" },
  { file: "image58", title: "Neville Letard" },
  { file: "image728" },
  { file: "image761", title: "Gillian" },
  { file: "image509", title: "Mark" },
  { file: "image590" },
  { file: "image788", title: "Leigh Downing" },
  { file: "image260", title: "Mark and Lauren in LA" },
  { file: "image795", title: "x, Mark and Lauren" },
  { file: "image766", title: "Lauren" },
  { file: "image879", title: "Louis and Michael in Portugal" },
  { file: "image658", title: "Michael and his sisters" },
  { file: "image72", title: "Louis at Madame Tussauds" },
  { file: "image529", title: "Mark in LA" },
  { file: "image697", title: "Mark" },
  { file: "image811", title: "Mark and Herb Klein" },
  { file: "image439", title: "Mark and Herb Klein" },
  { file: "image163", title: "Louis and Sophie" },
  { file: "image550", title: "Mathew" },
  { file: "image899", title: "Mark" },
  { file: "image661", title: "Mathew" },
  { file: "image272", title: "Tanya doing make up pre Fashion show" },
  { file: "image892", title: "Steven, Michael and Arthur" },
  { file: "image477", title: "Rene as Miss Subway" },
  { file: "image410", title: "Mark" },
  { file: "image151", title: "Gillian" },
  { file: "image474", title: "Trevor, Steven and Neil" },
  { file: "image660", title: "Seaton, Mark and Spencer" },
  { file: "image483", title: "Peter and The Pennay" },
  { file: "image559", title: "x and Mark" },
  { file: "image644", title: "Mark" },
  { file: "image756", title: "French Tea Party at Albion Road, Rondebosch, Cape Town. Patrick, Peter Harris and Murray Scannell" },
  { file: "image571", title: "Arabian Nights party, London. Maxi and Patrick" },
  { file: "image592", title: "Patrick" },
  { file: "image71", title: "Mark" },
  { file: "image625", title: "Mark" },
  { file: "image296", title: "Mark" },
  { file: "image1", title: "Mark and The Weep" },
  { file: "image737", title: "Seaton and Mark" },
  { file: "image665", title: "Mark, x and Spencer" },
  { file: "image885", title: "x, Gillian and Mark" },
  { file: "image310", title: "Mark" },
  { file: "image135", title: "Mark, Gillian and Seaton" },
  { file: "image822", title: "Liz Staniford and Andries Botha's wedding invite" },
  { file: "image88", title: "Patrick and model" },
  { file: "image839", title: "Noel Osborne, Stephen, Patrick Henri, Derek Lavarack and Alan Watt" },
  { file: "image164", title: "Stephen and Bernard" },
  { file: "image365", title: "Neil Starr and Henri" },
  { file: "image363", title: "Rene, Peter and Steven" },
  { file: "image370", title: "Gavin and Jackie" },
  { file: "image568", title: "Noel von Wildenrath and Rene" },
  { file: "image623", title: "Mark" },
  { file: "image672", title: "Patrick, Christine Popoff, Anina Cummings, Mark and Kerry at a 50's party." },
  { file: "image771", title: "Patrick, Glenda Holmes and Kevin Halcut" },
  { file: "image654", title: "Patrick, Mark and Arthur" },
  { file: "image27", title: "Thelma and Tony" },
  { file: "image346", title: "A night at The Zodiac nightclub. Alex Botha, Linda Basson, Marcel Wishura, Lianne Basson, Henri and Kerry" },
  { file: "image398", title: "Eddie de Lima and Tanya van Agthoven" },
  { file: "image373", title: "Maxi, Patrick and Stephen in Bantry Bay, Cape Town" },
  { file: "image287" },
  { file: "image783", title: "Sally" },
  { file: "image29", title: "Mathew" },
  { file: "image353", title: "Tanya van Agthoven and Leigh Downing" },
  { file: "image253", title: "Mark, Jackie and Spencer" },
  { file: "image890", title: "Mark" },
  { file: "image169", title: "Jackie" },
  { file: "image433", title: "Mark and Arthur" },
  { file: "image858", title: "Venice Road cottage" },
  { file: "image732", title: "Louis" },
  { file: "image67", title: "Patrick, Louis and Henri" },
  { file: "image382", title: "Adi and Gillian" },
  { file: "image357", title: "Henri" },
  { file: "image738", title: "Steven" },
  { file: "image780", title: "Steven" },
  { file: "image242", title: "Garth and Patrick" },
  { file: "image853", title: "Louis" },
  { file: "image291", title: "Gillian and Steven" },
  { file: "image493", title: "Gillian and Lauren" },
  { file: "image695", title: "Steven at Derek Meuvis's pool" },
  { file: "image716", title: "Kerry, Gillian and Heather" },
  { file: "image301", title: "Rene's invite" },
  { file: "image216", title: "Steven" },
  { file: "image329", title: "Steven at Zipps Johannesburg" },
  { file: "image258", title: "Steven" },
  { file: "image51", title: "Best Dressed Men" },
  { file: "image804", title: "Louis Christmas Card" },
  { file: "image215", title: "Lauren modelling in LA" },
  { file: "image387", title: "Mark and Steven in Amanzimtoti" },
];

export const NINETIES = [
  { file: "image724", title: "Garth and Henri in Durban" },
  { file: "image63", title: "Colin Mc Gree and Patrick" },
  { file: "image226", title: "Joan and her son at her graduation" },
  { file: "image859", title: "Garth and Henri" },
  { file: "image364", title: "Louis and Jessie in Vancouver, Canada" },
  { file: "image434", title: "Mark Lowe" },
  { file: "image205", title: "Michael, Patrick and Rene" },
  { file: "image146", title: "Seaton and Arthur" },
  { file: "image815", title: "Arthur and Stephane" },
  { file: "image582", title: "Kevin Mac Innes, Graham Moore, Steven, Richard Yell and Peter" },
  { file: "image593", title: "Steven" },
  { file: "image466", title: "Steven and Jackie" },
  { file: "image638", title: "Seaton" },
  { file: "image809", title: "Seaton and Steven" },
  { file: "image379", title: "Henri and Jonathan Arun, Wesyt Hampstead, London" },
  { file: "image579", title: "Steven, Henri and Garth at Garth's party in Durban" },
  { file: "image394", title: "Garth, Gary Searle, Garth Marquard and Boyd Ferguson" },
  { file: "image440", title: "David Ralphs, Peter Wishart and Alfie Bosman" },
  { file: "image225", title: "Henri and Steven" },
  { file: "image618", title: "Henri and Steven" },
  { file: "image438", title: "Michael" },
  { file: "image303", title: "Michael and Steven" },
  { file: "image846", title: "Steven, Michael and Steven's work colleagues" },
  { file: "image388", title: "Neil and Michael" },
  { file: "image883", title: "Ian and Gillian" },
  { file: "image845", title: "Steven" },
  { file: "image449", title: "Steven's favourite cafe at Mitchell Park, Durban" },
  { file: "image16", title: "Priscilla Blackie, Penny Brill, Nicola and Megan Blackie, Steven" },
  { file: "image501", title: "Patrick, Johan, Steven, Trevor and Gavin" },
  { file: "image383", title: "Lauren, Henri and Patrick" },
  { file: "image679", title: "Steven and Colin Hutt" },
  { file: "image870", title: "Patrick, Steven, Sally and Michael" },
  { file: "image527", title: "Michael, Patrick, Steven and Kevin MacInnes" },
  { file: "image213", title: "Sally and Steven" },
  { file: "image289", title: "Karen Ward and Richard" },
  { file: "image142", title: "330 Party Mark, Sally Chance, Patrick, Carrie and Carl Isaacs" },
  { file: "image32", title: "Mark, Carrie, Carmen Laurier, and Rafe Brown" },
  { file: "image302", title: "Jenna, Michael, Leonardo and Seaton" },
  { file: "image528", title: "Henri and Barrie in Canterbury" },
  { file: "image223", title: "Rocky Horror Party Patrick, Steven and Kevin Mc Innes" },
  { file: "image120", title: "Michael, Steven and Patrick" },
  { file: "image380", title: "Karen, Steven and Lisa" },
  { file: "image273", title: "Steven" },
  { file: "image261", title: "Steven and Arthur" },
  { file: "image203", title: "Trevor and Steven" },
  { file: "image107", title: "Steven" },
  { file: "image351", title: "Leigh, Heather Roche, Steven and Karen" },
  { file: "image392", title: "Allen and Steven" },
  { file: "image546", title: "Brettlee, Michael and Kevin" },
  { file: "image798", title: "Steven and Patrick" },
  { file: "image525", title: "Carolyn de Beyer, Shaun" },
  { file: "image358", title: "Steven" },
  { file: "image760", title: "Cheryl and Robert Johnson" },
  { file: "image855", title: "Colin Hutt" },
  { file: "image38", title: "Steven and Peter" },
  { file: "image317", title: "Steven and colleagues" },
  { file: "image190", title: "Steven, Sally, Patrick and Michael at MCQP Safari Camp Party 1998" },
  { file: "image136", title: "Jackie and Steven" },
  { file: "image182", title: "Choo, Kevin, Steven, Michael" },
  { file: "image172", title: "Steven and Patrick" },
  { file: "image671", title: "Steven and Patrick" },
  { file: "image524", title: "Adi and Gillian" },
  { file: "image478", title: "Gillian and Lisa Owen" },
  { file: "image531", title: "Neil and Gillian" },
  { file: "image649", title: "Karen, Gillian and Lisa" },
  { file: "image217", title: "Gillian, Neil and Spencer" },
  { file: "image860", title: "Sally and Steven" },
  { file: "image221", title: "Patrick and Jenna" },
  { file: "image82", title: "Patrick" },
  { file: "image246", title: "Steven" },
  { file: "image774", title: "Steven, Gillian and Michael" },
  { file: "image519", title: "Sally, Jenna, Michael and Neil" },
  { file: "image454", title: "Breda and Michael Crouch" },
  { file: "image769", title: "Kevin, Sally andPatrick" },
  { file: "image110", title: "Steven, Michael, Kevin and Patrick" },
  { file: "image746", title: "Kevin and Steven" },
  { file: "image708", title: "Michael" },
  { file: "image341", title: "Henri and Lauren, LA, California" },
  { file: "image872", title: "Lauren and Peter Amsden, Laurel Canyon, LA" },
  { file: "image518", title: "Seaton and Leonardo" },
  { file: "image907", title: "Steven, Sally and Patrick" },
  { file: "image617", title: "Louis in San Fransisco" },
  { file: "image530", title: "Louis in New York" },
  { file: "image683", title: "Michael" },
  { file: "image299", title: "Alan Whitehead and Choo" },
  { file: "image178", title: "Michael" },
  { file: "image156", title: "Michael and Patrick" },
  { file: "image368", title: "Jenna, Sally and Steven" },
  { file: "image800", title: "Sally" },
  { file: "image521", title: "Neil, Sally, Patrick and Michael" },
  { file: "image467", title: "Steven, Michael, Kevin McInnes and Patrick" },
  { file: "image257", title: "Colin, Douglas, Michael, Sally, Bretlee, Seaton, Patrick and Steven at The Trossachs, MacGregor" },
  { file: "image245", title: "Michael and Seaton" },
  { file: "image486", title: "Michael" },
  { file: "image776", title: "Patrick" },
  { file: "image902", title: "Patrick" },
  { file: "image33", title: "Gillian and Michael" },
  { file: "image484", title: "Patrick and Herb Klein" },
  { file: "image662", title: "Leonardo, Francois, Patrick, Seaton and Jenna" },
  { file: "image132", title: "Leonardo, Spencer, Michael, Patrick, Francois, Jenna, and Seaton" },
  { file: "image718", title: "Spencer, Seaton and Steven" },
  { file: "image842", title: "Joan, Seaton, Patrick and Brettlee" },
  { file: "image96", title: "Patrick, Brettlee, Neil, Michael and Sally" },
  { file: "image109", title: "Steven and Michael" },
  { file: "image137", title: "Steven and Heather" },
  { file: "image116" },
  { file: "image417", title: "Michael and Seaton" },
  { file: "image609", title: "Douglas" },
  { file: "image857", title: "Lisa, Karen, Sally, Lee and Glenda" },
  { file: "image751", title: "Steven, Frank Melman" },
  { file: "image542", title: "Petal and The Pennay" },
  { file: "image121", title: "Louis" },
  { file: "image427", title: "Louis, Illana and Gavin in Seattle" },
  { file: "image819", title: "Illana, Karen, Patrick and Louis in Seattle" },
  { file: "image898", title: "Patrick" },
  { file: "image372", title: "Patrick and Louis" },
  { file: "image543", title: "Louis" },
  { file: "image602", title: "Gavin, Illana and Louis" },
  { file: "image891", title: "Louis" },
  { file: "image875", title: "Louis and Patrick" },
  { file: "image115", title: "Michael" },
  { file: "image616", title: "Luke Davies, Henri, Neil Farrelly and Barrie Hadfield in London" },
  { file: "image175", title: "Luke, Peter White, Henri and Barrie" },
  { file: "image347", title: "Greg Davies, Henri, Peter and Luke in The Fridge, Brixton London" },
  { file: "image534", title: "Barrie and Henri in The Fridge, Brixton, London" },
  { file: "image362", title: "Henri, Luke and Barrie. Christmas in West Hampstead, London" },
  { file: "image719", title: "Oliver Ellis and Henri at Gay Pride 94 in London" },
  { file: "image335", title: "Henri and Jonathan Arun at Gay Pride" },
  { file: "image681", title: "Noel and Rene" },
  { file: "image411", title: "Noel" },
  { file: "image498", title: "Michael's 40th birthday. Michael and Spencer" },
  { file: "image843", title: "Jenna, Tony Gois, Seaton and Rene" },
  { file: "image442", title: "Patrick and Steven" },
  { file: "image165", title: "Neil, Keith Schultz and Sally" },
  { file: "image807", title: "Patrick and Michael at MCQP Twinkly Sea Party 1996" },
  { file: "image770", title: "Patrick and Sally" },
  { file: "image140", title: "Steven and Patrick" },
  { file: "image869", title: "Patrick and Dada" },
  { file: "image268" },
  { file: "image56", title: "Patrick, Kevin and Michael" },
  { file: "image642", title: "Patrick" },
  { file: "image256", title: "Kevin" },
  { file: "image810", title: "Kevin" },
  { file: "image79", title: "Steven" },
  { file: "image241", title: "Steven" },
  { file: "image553" },
  { file: "image62", title: "The Lot Hotel, En Bokek, the Dead Sea, Israel. The site of the original Sodom and the start of my relationship with Barrie." },
  { file: "image418", title: "Henri in the Dead Sea" },
  { file: "image102", title: "Henri" },
  { file: "image705", title: "Barrie" },
  { file: "image408", title: "Barrie, Shlommie and Henri at En Gedi, The Dead Sea, Israel" },
  { file: "image131", title: "Barrie" },
  { file: "image337", title: "Henri on the Bishop's throne, The Church of the Holy Sepulchre, Jerusalem, Israel" },
  { file: "image835", title: "Rene and Karen" },
  { file: "image20", title: "Sally, Steven and Richard" },
  { file: "image176", title: "Henri and Garth, Spitalfields, London" },
  { file: "image473", title: "Luke and Barrie" },
  { file: "image112", title: "Peter Wishart and Garth, Spitalfields, London" },
  { file: "image511", title: "Peter" },
  { file: "image238", title: "Garth and Rafe Brown, Spitalfields, London" },
  { file: "image13", title: "Luke and Henri" },
  { file: "image361", title: "Barrie and Henri" },
  { file: "image405", title: "Onion Ring 20th year reunion. Trevor, Ian, Adi, Peter, Sally, Mrs Roche, Joan, Pam and Karen" },
  { file: "image668", title: "Jenna and Seaton" },
  { file: "image764", title: "Sean Keegan and Peter" },
  { file: "image397", title: "Shaun, Carolyn and Micheal Cheze" },
  { file: "image106", title: "Kevin, Patrick and Steven" },
  { file: "image74", title: "Steven and Colin" },
  { file: "image60", title: "Seaton, Michael and Rene" },
  { file: "image591", title: "Steven" },
  { file: "image598", title: "Garth and Todd Barry. Spitalfields, London" },
  { file: "image170", title: "Steven" },
  { file: "image722", title: "Kevin and Steven" },
  { file: "image596", title: "Steven" },
  { file: "image435", title: "Steven and Frank Melman" },
  { file: "image865", title: "Henri and Mark Davis in the DJ booth of Heaven, London" },
  { file: "image188", title: "Mark Davis" },
  { file: "image712", title: "Henri at Mark's flat, Battersea, London" },
  { file: "image330", title: "Steven" },
  { file: "image25", title: "Henri- Trade membership card" },
  { file: "image881", title: "James Moffat and Henri, Spitalfields, London" },
  { file: "image540", title: "James, Barrie and Henri" },
  { file: "image469", title: "Steven" },
  { file: "image714", title: "Steven" },
  { file: "image731", title: "Henri and Mark Cioli, England" },
  { file: "image444", title: "Steven" },
  { file: "image338" },
  { file: "image219", title: "Henri in Cheshire" },
  { file: "image195", title: "Cheryl and Patrick" },
  { file: "image655", title: "Sally and Jenna" },
  { file: "image83", title: "Steven and Patrick" },
  { file: "image64", title: "Arthur, Neil and Michael" },
  { file: "image76", title: "Choo, Alan Whitehead and Colin" },
  { file: "image601", title: "Rowan and Garth" },
  { file: "image517", title: "Steven and Garth" },
  { file: "image179", title: "Mark" },
  { file: "image772", title: "20th Reunion at The Georges 5. Treva, Steven, Jackie, Adi, Sally, Michael and Karen" },
  { file: "image403", title: "Steven compering Mr Axis" },
  { file: "image710", title: "Leigh and Duncan" },
  { file: "image646", title: "Steven" },
  { file: "image453", title: "Gavin and Jackie" },
  { file: "image322", title: "Jackie" },
  { file: "image791", title: "Jackie" },
  { file: "image897", title: "Michael and Louis" },
  { file: "image847", title: "Robbie Pfister and Michael" },
  { file: "image848", title: "Michael" },
  { file: "image429", title: "Jackie and Sally" },
  { file: "image54", title: "June Schmarmen, Leigh and Gillian" },
  { file: "image85", title: "Josef, Adi and Neil" },
  { file: "image651", title: "Neil and Michael" },
  { file: "image824", title: "Garth and Henri in Durban" },
  { file: "image715", title: "Peter White's Mother NYE Party" },
  { file: "image447", title: "Nicole, Upstate New York" },
  { file: "image381", title: "Henri" },
  { file: "image42", title: "Henri in Chloe's flat, Egerton Gardens, South Kensington, London" },
  { file: "image632", title: "Henri in New York" },
  { file: "image98", title: "John Truex, New York" },
  { file: "image269", title: "Ian, New York" },
  { file: "image548", title: "Henri, New York" },
  { file: "image184", title: "Gregory Pierrotti, New York" },
  { file: "image396", title: "Henri" },
  { file: "image345", title: "Henri" },
  { file: "image758", title: "Chloe Rolfes and Henri in New York" },
  { file: "image565", title: "Henri working at Kin Khao, New York" },
  { file: "image485", title: "Christine, Henri and Guy, Kin Khao, New York" },
  { file: "image356", title: "Brad" },
  { file: "image840", title: "Henri" },
  { file: "image300", title: "Steven and Patrick" },
  { file: "image344", title: "Henri in Juice, Covent Garden, London" },
  { file: "image401", title: "David Ross" },
  { file: "image754", title: "Juice menu" },
  { file: "image757", title: "Craig" },
  { file: "image283", title: "Barrie and Henri" },
  { file: "image742", title: "First iMac Internet cafe in London" },
  { file: "image285", title: "Juice" },
  { file: "image259", title: "Art Gallery and Internet Cafe at Juice, Covent Garden, London" },
  { file: "image93" },
  { file: "image210", title: "Skweeze Juice Bar, Toronto, Canada" },
  { file: "image827", title: "Skweeze Juice Bar" },
];

export const TWOTHOUSANDS = [
  { file: "image706", title: "Henri and Barrie, Marrakesh, Morrocco" },
  { file: "image130", title: "Barrie, Henri, Steven and Joan" },
  { file: "image185", title: "Sally and Neil at Garth's pool, Durban" },
  { file: "image441", title: "Douglas, Patrick and Brettlee" },
  { file: "image689", title: "Michael" },
  { file: "image101", title: "Michael" },
  { file: "image436", title: "Henri, Mykonos" },
  { file: "image759", title: "Michael, Patrick and Seaton" },
  { file: "image92", title: "Patrick, Neil and Joan" },
  { file: "image4", title: "Douglas and Chris Weir" },
  { file: "image147", title: "Henri and Barrie sailing off Mykonos" },
  { file: "image97", title: "Douglas and Brettlee on their wedding day" },
  { file: "image143", title: "Barrie, Marrakesh, Morrocco" },
  { file: "image315", title: "Henri and Barrie, Marrakesh, Morrocco" },
  { file: "image866", title: "Michael, Patrick and Steven" },
  { file: "image539", title: "Henri and Barrie at Barrie's 30th birthday, London" },
  { file: "image626", title: "Seaton" },
  { file: "image432", title: "Seaton, Leonardo and Patrick" },
  { file: "image767", title: "Colin and Patrick" },
  { file: "image736", title: "Brettlee and Patrick" },
  { file: "image44", title: "Douglas and Patrick" },
  { file: "image779", title: "Neil, Treva, Seaton, Leonardo and Patrick" },
  { file: "image183", title: "MIchael and Douglas" },
  { file: "image294", title: "Michael" },
  { file: "image138", title: "Barrie, Blackheath, London" },
  { file: "image177", title: "Lauren, Blackheath, London" },
  { file: "image874", title: "Kevin and Steven" },
  { file: "image497", title: "Graham, Mark, James and Peter" },
  { file: "image189", title: "Frank Melman and Steven" },
  { file: "image693", title: "Arthur, Treva, Michael and Seaton" },
  { file: "image407", title: "Seaton and Michael" },
  { file: "image581" },
  { file: "image37", title: "Michael" },
  { file: "image673", title: "Henri and Garth at Peter and Graham's house" },
  { file: "image622", title: "Henri" },
  { file: "image312", title: "Mark" },
  { file: "image664", title: "Henri, Garth and Rowan" },
  { file: "image192", title: "Darryl, Kim and Peter" },
  { file: "image270", title: "Michael, Steven and Patrick" },
  { file: "image801", title: "Garth's pool" },
  { file: "image305", title: "Henri at Garth's house" },
  { file: "image603", title: "Garth" },
  { file: "image6", title: "Barrie" },
  { file: "image563", title: "Barrie and Canadian Gordon Seaman at Peace Cottage" },
  { file: "image878", title: "Barrie outside Garth's house, Berea, Durban" },
  { file: "image229", title: "Henri, North Beach, Durban for The Gunston 500" },
  { file: "image631", title: "Barrie and Henri sailing" },
  { file: "image14", title: "Jamie and Henri sailing off Mallorca, Spain" },
  { file: "image275", title: "Jamie the most wonderful dog in the world in Mallorca" },
  { file: "image55", title: "Barrie, Portals Vells, Mallorca" },
  { file: "image707", title: "Patrick and Neil" },
  { file: "image336", title: "Cheryl at Garth's house" },
  { file: "image31", title: "Mark, Lauren and David, Mallorca" },
  { file: "image547", title: "Mark, Lauren, Henri and Lauren in Mallorca" },
  { file: "image105", title: "David, Lauren and Henri, Mallorca" },
  { file: "image849", title: "David Wannamaker, Lauren, Henri, Barrie, Lauren and Ruben, Mallorca" },
  { file: "image293", title: "Ruben Singer, Lauren Estagarribia, Lauren and Henri sailing off Mallorca" },
  { file: "image94", title: "Patrick and Garth at Garth's house" },
  { file: "image87", title: "Henri in Madurai, India" },
  { file: "image841", title: "Henri, Barrie and Jamie sailing in Mallorca" },
  { file: "image555", title: "At home in Blackheath, London" },
  { file: "image248", title: "Onion Ring 30th Reunion Party. Rowan, Tanya, Leigh and Garth" },
  { file: "image597", title: "Peter, Sally, Gillian and Karen" },
  { file: "image262", title: "Heather and Mark" },
  { file: "image234", title: "Rowan, Mark and Patrick" },
  { file: "image871", title: "Steven, Graham and Peter" },
  { file: "image367", title: "Heather and Garth" },
  { file: "image400", title: "Treva and Steven" },
  { file: "image22", title: "Patrick and Carla Thompson" },
  { file: "image873", title: "Mark Lowe and Heather" },
  { file: "image59", title: "Rowan" },
  { file: "image240", title: "Rowan and Debbie Reynolds" },
  { file: "image494", title: "Guy Woods" },
  { file: "image906", title: "Garthe, Henri and Leigh" },
  { file: "image168", title: "Guy and Heather" },
  { file: "image321", title: "Sally, Michael, Treva, Steven and Joan" },
  { file: "image735" },
  { file: "image318", title: "Adi, Stephane, Arthur and Michael" },
  { file: "image557", title: "Steven and Henri" },
  { file: "image127", title: "Barrie, Henri, Angel and Cindy" },
  { file: "image148", title: "Cindy and Angel" },
  { file: "image304", title: "Henri and Barrie" },
  { file: "image680", title: "Daniel, Jenna, Sally, Neil, Rowan and Seaton" },
  { file: "image208", title: "Barrie, Henri, Steven, Joan and Sharon Spradbury" },
  { file: "image912", title: "Garth, Patrick and Henri" },
  { file: "image233", title: "Patrick, Henri and Sally at Garth's house" },
  { file: "image545", title: "Garth, Steven and Henri" },
  { file: "image640", title: "Steven and Henri" },
  { file: "image39", title: "Steven, Garth, Patrick, Henri and Jackie" },
  { file: "image480", title: "Henri and Jamie, St Margaret's Bay" },
  { file: "image594", title: "Patrick and Henri, St Margaret's Bay" },
  { file: "image729", title: "Barrie" },
  { file: "image633", title: "Barrie and Jamie" },
  { file: "image159", title: "Barrie" },
  { file: "image472", title: "St Margaret's Bay, Kent, England" },
  { file: "image561", title: "Jamie and Barrie" },
  { file: "image369", title: "Henri and Jamie on the white cliffs at St Margaret's Bay, Kent, England" },
  { file: "image314", title: "Chloe and Henri at St Margaret's Bay" },
  { file: "image893", title: "Michael van Rensburg at St Margaret's Bay, Kent, England" },
  { file: "image450", title: "Henri and Chloe at Great Dixter, East Sussex, England" },
  { file: "image576", title: "Josef and Sally" },
  { file: "image564", title: "Michael and Seaton" },
  { file: "image220", title: "Steven" },
  { file: "image506", title: "Steven" },
  { file: "image126", title: "Luke and Henri, Elia Beach, Mykonos" },
  { file: "image787", title: "Steven" },
  { file: "image619", title: "Hayley, Penny Brill, Treva, Steven and Nicola Blackie" },
  { file: "image451", title: "Michael and Patrick" },
  { file: "image46", title: "Arthur and Michael Crouch" },
  { file: "image621", title: "Joan, Seaton, Toni Gois and Michael" },
  { file: "image426", title: "Kevin, Steven and Michael at The Trossachs, Mac Gregor, Cape" },
  { file: "image889", title: "Michael and Patrick" },
  { file: "image43", title: "Seaton, Douglas and Michael" },
  { file: "image610", title: "Steven" },
  { file: "image26", title: "Patrick, Brettlee and Sally" },
  { file: "image513", title: "Douglas, Sally and Steven" },
  { file: "image41", title: "Patrick, Brettlee, Douglas, Seaton, Sally and Michael" },
  { file: "image720", title: "Sally" },
  { file: "image514", title: "Douglas, Seaton, Steven, Sally and Michael" },
  { file: "image627", title: "Colin, Steven, Seaton, Patrick, Sally, Douglas and Brettlee" },
  { file: "image80", title: "Neil" },
  { file: "image237", title: "Michael and Sally" },
  { file: "image134", title: "Jenna, Sally and Steven" },
  { file: "image274", title: "Brettlee, Douglas, Jayshree and Patrick" },
  { file: "image745", title: "Joan, Priscilla and Penny" },
  { file: "image606", title: "Sally, Jenna, Michael and Neil" },
  { file: "image677" },
  { file: "image910", title: "Brettlee and Douglas" },
  { file: "image416", title: "Francois, Brettlee, Sally, Kevin and Spiro" },
  { file: "image903", title: "Michael" },
  { file: "image520", title: "Steven, Sally, Kevin, Neil and Michael" },
  { file: "image781", title: "Patrick, Steven and Sally" },
  { file: "image471", title: "Kevin and Colin" },
  { file: "image421", title: "Patrick" },
  { file: "image149", title: "Henri and Patrick, Mallorca" },
  { file: "image282", title: "Patrick, Henri and Barrie" },
  { file: "image103", title: "Henri and Patrick at C'an Petra Marche in Deia, Mallorca" },
  { file: "image199", title: "Patrick and Henri" },
  { file: "image820", title: "Peter White, Mallorca" },
  { file: "image191", title: "Peter, Mallorca" },
  { file: "image200", title: "Mallorca pool" },
  { file: "image30", title: "Lauren and Henri sailing" },
  { file: "image28", title: "Lauren at old military base, Mallorca" },
  { file: "image342", title: "Lauren and super yacht, Mallorca" },
  { file: "image277", title: "Megan de Beyer and Henri, Mallorca" },
  { file: "image5", title: "Henri and Barrie, Sydney Australia" },
  { file: "image47", title: "Colin, Seaton, Patrick, Treva, Sally, Nicky and Karen" },
  { file: "image385", title: "Cheryl and her cat" },
  { file: "image667", title: "Kevin, and Seaton" },
  { file: "image308", title: "Kevin" },
  { file: "image607", title: "Kevin and Seaton" },
  { file: "image2", title: "Michael, Seaton and Noel" },
  { file: "image292", title: "Barrie and Henri, Marseille, France" },
  { file: "image211", title: "Barrie and Henri get married, Canterbury, Kent, England" },
  { file: "image648", title: "Sally and Steven" },
  { file: "image650", title: "The Onion Ring 40th Reunion. Treva, Karen and Patrick" },
  { file: "image537", title: "Gillian and Gillian" },
  { file: "image773", title: "Andrew, Cheryl and Mario" },
  { file: "image723", title: "Henri, Garth and Rowan" },
  { file: "image476", title: "Gillian and Karen" },
  { file: "image280", title: "Steven" },
  { file: "image838", title: "Stephane, Leonardo and Arthur" },
  { file: "image66", title: "Jackie and Sally" },
  { file: "image544", title: "Michael" },
  { file: "image750" },
  { file: "image895" },
  { file: "image741" },
  { file: "image77" },
];

export const GALLERIES = {
  "the-stardust": THE_STARDUST,
  "the-boudoir": THE_BOUDOIR,
  "steven": STEVEN,
  "70s": SEVENTIES,
  "80s": EIGHTIES,
  "90s": NINETIES,
  "2000": TWOTHOUSANDS,
};
