/**
 * Content for the Stardust & Beyond site - a 1970s disco photo archive.
 * Generated from the .docx export by scripts/import-docx.py.
 * Each gallery item is { file, title? } - `title` is the photo caption.
 * Array order = display order.
 */

export const SITE = {
  name: "Stardust & Beyond",
  role: "A 1970s disco, and the friends who lived it",
  url: "https://stardustandbeyond.com",
};

export const SOCIAL = {
  instagram: "",
  bluesky: "",
  whatsapp: "https://chat.whatsapp.com/FGV5V4qmuPYJjy2lxdZZcV?s=sw&p=a&mlu=4",
};

// The club photo that leads the site (first uncaptioned image in The Stardust).
export const LEAD = { kind: "the-stardust", file: "image575" };

// Section registry - drives the nav, the home "rooms" grid, and page builders.
export const SECTIONS = [
  { kind: "the-stardust", label: "The Stardust", href: "the-stardust.html", unit: "photos", blurb: "The club, 1975." },
  { kind: "the-boudoir", label: "The Boudoir", href: "the-boudoir.html", unit: "photos", blurb: "Steven's bedroom, and The Onion Ring." },
  { kind: "steven", label: "Steven", href: "steven.html", unit: "photos", blurb: "Steven Roche, aka Margot." },
  { kind: "70s", label: "70’s", href: "70s.html", unit: "photos", blurb: "The decade it all began." },
  { kind: "80s", label: "80’s", href: "80s.html", unit: "photos", blurb: "Bigger, brighter, bolder." },
  { kind: "90s", label: "90’s", href: "90s.html", unit: "photos", blurb: "The friends, years on." },
  { kind: "2000", label: "2000s", href: "2000.html", unit: "photos", blurb: "Into the new century." },
];

export const STARDUST_TEXT = [
  "The Stardust was the only Gay club in Durban. It was a secret and only gay people and their friends knew about it. There was no sign on the anonymous door and you had to climb to the 3rd floor of a building down a dark alleyway between 2 of the main roads right in the centre of the city. Joan Dickman and I were taken there by Hilton Wolman in early January 1975. It was a small nightclub with a tiny dance floor and a bar. This was a completely new, scary and shocking world to us. I introduced the club to Patrick, Rory and Cindy and we had so much fun on the dancefloor that we began going regularly. We felt truly liberated there. In April Joan and I went to our first drag competition. Miss Natal 1975. The club was jam packed filled with screaming supporters of all these beautiful “girls”. We had never seen anything like it before. Joan suddenly realised that the queen who came third was in her maths class at university. The following Monday in the maths class she leant forward, tapped him on the shoulder and said “You looked fabulous on Friday night”. So began our friendship with Steven. From that moment onwards our lives would never be the same again.",
];

export const BOUDOIR_TEXT = [
  "The boudoir was the name given to Steven Roche’s bedroom. It was an annex at the back of the Roche family home where a group of very close knit friends used to congregate and hang out all the time. This group was eventually nicknamed The Onion Ring. We used to turn up at the Roche home where the doors were always open and walk through the house greeting other members of the family until we got to Steven’s boudoir where we would spend hours sitting around chatting and drinking endless cups of tea. Occasionally these gatherings would turn into little parties with hysterical laughter and lots of fun and games."
];

export const THE_STARDUST = [
  { file: "image882", title: "The Stardust DJ Peter Wheeler" },
  { file: "image768", title: "Steven Roche aka Margot" },
  { file: "image618", title: "Alan Horn, Patrick Brill and Cindy West" },
  { file: "image526", title: "Cindy West" },
  { file: "image73" },
  { file: "image74", title: "An invitation to the Miss Sunshine at The Butterworth Hotel in Durban" },
  { file: "image346", title: "Rodney Symes, Eric Reeves, Carol and Barry. Eric and Barry were the owners of The Stardust." },
  { file: "image226", title: "Miss Stardust 1976 contestants" },
  { file: "image678", title: "Miss Stardust 1976 Jackie, Gillian, Steven and Vanessa" },
  { file: "image565", title: "Steven" },
  { file: "image374", title: "Vanessa and Steven Miss Stardust 1976" },
  { file: "image309", title: "Vanessa, Steven, Gillian and Eric Reeves with Roy Weir as DJ" },
  { file: "image912", title: "Steven at Rocky Horror party" },
  { file: "image467" },
  { file: "image277", title: "Miss Stardust 1977. Grant Patterson and Steven" },
  { file: "image228", title: "Miss Stardust 1977" },
  { file: "image694", title: "Steven crowning Miss Stardust 1977" },
  { file: "image705", title: "Lesley Wallace" },
  { file: "image213", title: "Steven and Gary" },
  { file: "image877", title: "Gary Williams" },
  { file: "image162", title: "Steven doing cabaret at The Stardust" },
  { file: "image483", title: "Darryl Rogers" },
  { file: "image26", title: "Darryl Rogers, Kevin Rogers and Gillian Lenton" },
  { file: "image130", title: "Darryl and Gillian" },
  { file: "image659", title: "Henry Davies and Darryl" },
  { file: "image823", title: "Joan Dickman and Pam Harmse" },
  { file: "image828", title: "Dickie Conradie" },
  { file: "image83", title: "Rene Kent" },
  { file: "image740", title: "Sophie Symes" },
  { file: "image848", title: "Gavin Woolf aka The Weep" },
  { file: "image930", title: "Steven and Craig Peetz" },
  { file: "image293", title: "Steven, Craig, Ronnie Botha, Henry and Mark Griffin" },
  { file: "image840", title: "Henry and Lauren Shipton" },
  { file: "image902", title: "Lauren and Ian Perry" },
  { file: "image115", title: "Craig as Miss Natal 1977" },
  { file: "image287", title: "Kerry Bennett at The Stardust" },
  { file: "image348", title: "Lauren" },
  { file: "image310", title: "Miss South Africa Ian, Leslie Wallace, Gary Moore, Steven" },
  { file: "image685", title: "Leslie, Ian and Steven" },
  { file: "image372", title: "Ian Perry winning Miss South Africa" },
  { file: "image725", title: "Miss South Africa Lesley Wallace, Ian Perry, Steven Roche, Gillian and Peter Wheeler The Stardust DJ." },
  { file: "image353" },
  { file: "image925", title: "Steven doing Martie the Martian" },
  { file: "image550", title: "Lauren" },
  { file: "image755", title: "Marcel Wishura" },
  { file: "image759", title: "Ian and Peter Pienaar, the owner of the Stardust" },
];

export const THE_BOUDOIR = [
  { file: "image370", title: "Keith, Trevor Norris, Mark Griffin and Henry Davies" },
  { file: "image447", title: "Steven, Keith, Trevor, Henry, Mark, Michael Hunter Smith, Elaine Welsh, Jackie Bryant, Rodney Symes, Patrick Brill, Steven Kent and Karen Ward" },
  { file: "image742", title: "Patrick, Rene and Rodney" },
  { file: "image394", title: "Steven" },
  { file: "image302", title: "Jackie, Mark & Steven" },
  { file: "image281", title: "Sally Fisher and Steven" },
  { file: "image288", title: "Steven dressed up to crown Miss Stardust 1977" },
  { file: "image719", title: "Henry sewing Steven's dress" },
  { file: "image909", title: "Joan, Margaret Mott Adams, Steven and Patrick at Steven's birthday party in the Boudoir." },
  { file: "image908", title: "Henry at Steven's birthday party" },
  { file: "image437", title: "Jackie, Henry, Pam, Steven and Conrad" },
  { file: "image181", title: "Jackie, Mrs Roche and Steven aka Rene" },
  { file: "image665", title: "Richard Rufus Ellis and Steven" },
  { file: "image658", title: "Outside the Boudoir. Rene, Jackie, Mark, Gillian and Steven" },
  { file: "image413", title: "Steven and Mark" },
  { file: "image290", title: "Thelma, Mr Roche and Gillian" },
  { file: "image592", title: "Gillian" },
  { file: "image328", title: "Gillian" },
  { file: "image668", title: "Keith and Steven" },
  { file: "image282", title: "Henry" },
  { file: "image623", title: "Gavin, Illana Woolf and Henry" },
  { file: "image332", title: "Steven and Henry" },
];

export const STEVEN = [
  { file: "image400", title: "Steven" },
  { file: "image41", title: "Steven" },
  { file: "image517", title: "Steven and Jackie" },
  { file: "image391", title: "Steven and Mark" },
  { file: "image916", title: "Steven and Adi" },
  { file: "image108", title: "Steven and Mark" },
  { file: "image559", title: "Steven modelling in Overport City photographed by his father" },
  { file: "image469" },
  { file: "image5" },
  { file: "image274" },
  { file: "image107", title: "Peter Moffat and Steven" },
  { file: "image827", title: "Steven in his back garden" },
  { file: "image57", title: "Steven and Rene- The Eclair Sisters" },
  { file: "image456", title: "Steven and Rene" },
  { file: "image529", title: "Adi and Steven" },
  { file: "image126", title: "Steven as Margot" },
  { file: "image728", title: "Steven and Gary" },
  { file: "image203", title: "Trevor and Steven" },
  { file: "image289", title: "The Eclair Sisters- Trish and Trash Eclair" },
  { file: "image295", title: "Steven" },
  { file: "image396", title: "The Eclair Sisters" },
  { file: "image369", title: "Steven and Jackie's travels in Europe" },
  { file: "image481", title: "Steven" },
  { file: "image964", title: "Adi and Steven" },
  { file: "image270" },
  { file: "image229", title: "Steven's collage" },
  { file: "image33", title: "Steven's collage" },
  { file: "image457", title: "Steven doing cabaret" },
];

export const SEVENTIES = [
  { file: "image839", title: "Henry and Cindy shopping in Durban" },
  { file: "image32", title: "Rory West and Patrick Brill as trainee chefs at The Elangeni Hotel, Durban" },
  { file: "image850", title: "Cindy in Johannesburg" },
  { file: "image743", title: "Cindy" },
  { file: "image110", title: "Cindy and Marcel Wishura" },
  { file: "image405", title: "Cindy in Johannesburg" },
  { file: "image176", title: "Henry at The Linger Longer restaurant in Johannesburg" },
  { file: "image646", title: "Richard Lawton" },
  { file: "image358", title: "Trevor, Anick his sister and Michael" },
  { file: "image294", title: "Michael and Elaine" },
  { file: "image354", title: "Ronnie Botha at Marchpane Terraces" },
  { file: "image787", title: "Henry and Cindy at Marchpane Terraces, Yeoville, Johannesburg" },
  { file: "image836", title: "Anthony, Cindy, Patrick and Henry at Marchpane Terraces, Yeoville, Johannesburg" },
  { file: "image862", title: "Cindy messing around in The Landrost Hotel, Johannesburg" },
  { file: "image349", title: "Cindy and Henry" },
  { file: "image672", title: "Patrick" },
  { file: "image98", title: "Living at The Hoffman New Yorker, Hillbrow, Johannesburg" },
  { file: "image662", title: "Henry In The Hoffman New Yorker, Hillbrow, Johannesburg" },
  { file: "image884", title: "Cindy and Henry in The Hoffman New Yorker, Hillbrow, Joannesburg" },
  { file: "image804", title: "Michael Hunter Smith and Treva Norris in the army" },
  { file: "image15", title: "Michael, Bernard Hatch and Treva in the army" },
  { file: "image199", title: "Trevor and Michael" },
  { file: "image766", title: "Patrick and Kerry in Raffles, The Maharani Hotel, Durban" },
  { file: "image334", title: "Patrick, Kerry and Mario Rodrigues at Raffles in The Maharani Hotel Durban" },
  { file: "image563", title: "Lawrence Potgieter and Cindy in The Hoffman New Yorker, Hillbrow, Johannesburg" },
  { file: "image593", title: "Illana Woolfe, Cindy West and Lawrence Potgieter seeing Cindy off to London, Jan Smuts airport, Johannesburg" },
  { file: "image941", title: "Illana Woolfe, Cindy West and Henry Davies" },
  { file: "image876", title: "Illana and Henry at Jan Smuts airport to see Cindy leave for London" },
  { file: "image155" },
  { file: "image475", title: "Henry Davies in the army at Bourkes Luck" },
  { file: "image903", title: "Henry Davies in the army at The Potholes, Bourkes Luck" },
  { file: "image860", title: "Henry Davies in the army, Bourkes Luck, Eastern Transvaal" },
  { file: "image697" },
  { file: "image700", title: "Warwick May" },
  { file: "image693", title: "Medieval Party. Heather, Jackie, Gillian, Steven, Trevor and Rene" },
  { file: "image356", title: "Steven and Gillian" },
  { file: "image611", title: "Steven, Rene and Gillian" },
  { file: "image314", title: "and Trevor" },
  { file: "image264", title: "Trevor" },
  { file: "image669", title: "Michael, Treva and Richard" },
  { file: "image843", title: "Trevor" },
  { file: "image871", title: "Steven, Richard and Rene" },
  { file: "image412", title: "Michael and Trevor" },
  { file: "image804-2" },
  { file: "image858", title: "Michael, Lindi and Trevor" },
  { file: "image910", title: "Michael" },
  { file: "image462", title: "Trevor and Sally" },
  { file: "image980", title: "Graham Doubell and Richard" },
  { file: "image607", title: "Sally, Steven and Richard" },
  { file: "image683", title: "Sally and Karen" },
  { file: "image180", title: "Trevor" },
  { file: "image788", title: "Trevor and Charlie Brown" },
  { file: "image242", title: "Michael" },
  { file: "image253", title: "Steven" },
  { file: "image829", title: "Karen" },
  { file: "image122", title: "Mark and Treva" },
  { file: "image806", title: "Steven, Keith and Michael" },
  { file: "image773", title: "Thelma and Tony" },
  { file: "image885", title: "Michael, Trevor and Steven" },
  { file: "image736", title: "Treva, Steven and Richard" },
  { file: "image209", title: "Steven" },
  { file: "image924", title: "Illana" },
  { file: "image269", title: "Rene" },
  { file: "image718", title: "Lauren got shot" },
  { file: "image215", title: "Ivan Kruger" },
  { file: "image831", title: "Patrick and Wally Hayward at the Star Wars party at The Zodiac" },
  { file: "image4", title: "Kerry and Wally" },
  { file: "image573", title: "Louis de Araujo" },
  { file: "image527", title: "Rory's 21st birthday, London Rory West" },
  { file: "image641", title: "Cindy West" },
  { file: "image298", title: "Henry and Chin Soon at Rory's 21st birthday" },
  { file: "image547", title: "Rory West" },
  { file: "image16", title: "Susie and Henry" },
  { file: "image416", title: "The Leopard and Cindy" },
  { file: "image192", title: "Rory West, London" },
  { file: "image866", title: "Darryl Rogers" },
  { file: "image661", title: "Kerry Bennett modelling The Walsh Marais Gallery kaftan" },
  { file: "image201", title: "Henry Davies working at Thats It, Hillbrow, Johannesburg" },
  { file: "image682", title: "Henry Davies, Thats It boutique, Hillbrow, Johannesburg" },
  { file: "image29", title: "Lauren Shipton and Rocky Farren" },
  { file: "image261", title: "The Leopard, Rory and Henry" },
  { file: "image616", title: "Henry Davies and Darryl Rogers" },
  { file: "image149", title: "Darryl Rogers" },
  { file: "image145", title: "Cindy West. Chelsea Studios, Chelsea, London" },
  { file: "image7", title: "Rory West and Henry Davies, London" },
  { file: "image382", title: "Henry at Ronnie Botha's flat off Botanic Gardens Road" },
  { file: "image927", title: "Simone and Darryl Rogers in Ronnie Botha's flat" },
  { file: "image861", title: "Henry Davies hanging out at Ronnie Botha's flat" },
  { file: "image254", title: "Darryl Rogers" },
  { file: "image533", title: "Steven Roche and Jackie Bryant" },
  { file: "image297", title: "Steven, Alwyn, Arthur Garrod and Jackie in Mykonos" },
  { file: "image111", title: "Rory West" },
  { file: "image379", title: "Cindy" },
  { file: "image443", title: "Louis de Araujo, Illana Woolfe and Michael van Rensburg at Jan Smuts airport for Rory's flight to London" },
  { file: "image1107", title: "Rory goes to London. Jan Smuts airport, Johannesburg. Rory West" },
  { file: "image914", title: "Rory West, Illana Woolfe and Henry Davies at Jan Smuts airport for Rory's farewell to London" },
  { file: "image758", title: "Louis de Araujo and Illana Woolfe seeing Rory off to London, Jan Smuts airport, Johannesburg" },
  { file: "image485", title: "Darryl Rogers" },
  { file: "image763", title: "Lauren" },
  { file: "image355", title: "Janet Marchpane" },
  { file: "image331", title: "Cindy" },
  { file: "image36", title: "Cindy and Henry" },
  { file: "image487", title: "Louis Christmas Card 1978" },
  { file: "image215-2", title: "Rory getting ready for New Years Eve party London" },
  { file: "image109", title: "Cindy and Rory" },
  { file: "image166", title: "Rory and Cindy" },
  { file: "image372", title: "Bette Midler at The Palladium, London, 1978" },
  { file: "image841", title: "Louis' brilliant cartoon" },
  { file: "image168", title: "Darryl Rogers at The Zodiac" },
  { file: "image502", title: "The Skyline Bar, Hillbrow, Johannesburg" },
  { file: "image269-2" },
  { file: "image615" },
  { file: "image1161" },
  { file: "image454", title: "Alan Whitehead" },
  { file: "image201-2", title: "Danny, Peter and Alan Whitehead" },
  { file: "image1018", title: "Danny, Leslie, Alan Whitehead and Greg Reichman" },
  { file: "image1095", title: "Rocky Horror Party. Michael, Adi and Arthur" },
  { file: "image834", title: "The Dungeon Club, Johannesburg" },
  { file: "image716", title: "Adi" },
  { file: "image272", title: "Marcel Wishura" },
  { file: "image53", title: "Cindy West in Paris" },
  { file: "image698", title: "Steven and Neil" },
  { file: "image441", title: "Rory in the army In Potschefstroom" },
  { file: "image256", title: "Louis's Christmas Card" },
  { file: "image326", title: "Rene as Miss Subway" },
  { file: "image40", title: "Neil Starr" },
  { file: "image47", title: "Mathew Kelly" },
  { file: "image506", title: "Spencer Pillay and Rene" },
  { file: "image363", title: "Noel van Wildenrath and Henry Davies" },
  { file: "image918", title: "Noel van Wildenrath" },
  { file: "image531", title: "Brian Hirst, Michael Rhodes, Graham Simpson, Warwick and Andrew van der Merwe" },
  { file: "image576", title: "Warwick" },
  { file: "image794", title: "Andrew van der Merwe" },
  { file: "image1023", title: "Dudley Manicom" },
  { file: "image245", title: "Peter Moffat aka Petal" },
  { file: "image285", title: "Louis' Cartoon" },
  { file: "image484", title: "Darryl Rogers" },
  { file: "image3", title: "Darryl Rogers" },
  { file: "image403", title: "Darryl" },
  { file: "image829-2", title: "Peter Wheeler, Tony de Klerk , Aubrey Walsh and Greg Reichman" },
  { file: "image601", title: "70's Pool Party Anthony Harris, Peter Wheeler, Tony de Klerk, Aubrey Walsh and Greg Reichman" },
  { file: "image728", title: "Anthony Harris" },
  { file: "image186", title: "Greg Reichman" },
  { file: "image854", title: "Aubrey Walsh" },
  { file: "image711", title: "Paul du Plessis" },
  { file: "image564", title: "Steven in Greece" },
  { file: "image785", title: "Steven" },
  { file: "image777", title: "Arthur Garrod" },
  { file: "image364", title: "Arthur Garrod, SAA" },
  { file: "image744", title: "Arthur Garrod" },
  { file: "image705", title: "Arthur Garrod" },
  { file: "image370", title: "Jean de Cruz" },
  { file: "image510", title: "Jean de Cruz and Alan Froneman aka Alice" },
  { file: "image1099", title: "Richard Plank" },
  { file: "image271", title: "Richard Plank" },
  { file: "image38", title: "Mario" },
  { file: "image770", title: "Tony de Klerk" },
  { file: "image25", title: "Tony de Klerk" },
  { file: "image734", title: "Jeremy Taylor" },
  { file: "image875", title: "Stephan and Greg Reichman" },
  { file: "image29-2", title: "Stephan and Greg Reichman" },
  { file: "image1039", title: "Stephan" },
  { file: "image233", title: "Craig Peetz" },
  { file: "image981", title: "Mark Griffin and Arthur Garrod" },
  { file: "image1106", title: "Greg Reichman, Noel van Wildenrath, Ian Perry and Craig Peetz" },
  { file: "image975", title: "Noel van Wildenrath and Ian Perry" },
  { file: "image862-2", title: "Craig Peetz and Ian Perry" },
  { file: "image356-2", title: "Greg Reichman, Noel van Wildenrath Ian Perry and Craig Peetz" },
  { file: "image71", title: "Craig Peetz" },
  { file: "image279", title: "Craig Peetz and Ian Perry" },
  { file: "image1171", title: "Craig Peetz" },
  { file: "image1101", title: "Jeremy Taylor" },
  { file: "image174", title: "John Bekker and Simon Trace" },
  { file: "image707", title: "Greg Reichman, Butch Loggenberg, Peter Cole and Hilton Davis" },
  { file: "image762", title: "Kerry" },
  { file: "image777-2", title: "Janet Doby and Patrick" },
  { file: "image330", title: "Patrick and Kerry" },
  { file: "image99", title: "Durban Tech" },
  { file: "image573-2", title: "On the roof of The Natal Technikon, 567 Smith Street, Durban. Tanya van Agthoven and Henry Davies" },
  { file: "image673", title: "Cindy on holiday" },
  { file: "image458", title: "The Together Bar, Hillbrow, Johannesburg" },
  { file: "image570", title: "Albie, Stephen Pritchard, Wally Haywood, Bernard Hatch and Henry getting ready for a party at Albie's parents house" },
  { file: "image695", title: "Darryl Rogers and Blane Mackintosh" },
  { file: "image247", title: "Darryl Rogers and Blane Mackintosh" },
  { file: "image297-2", title: "Darryl Rogers, Blane Mackintosh, Wally Hayward and Albie van Loggenberg" },
  { file: "image1001", title: "Bernard Hatch and Henry Davies" },
  { file: "image73", title: "Wally Hayward and Stephen Pritchard" },
  { file: "image493", title: "Wally Hayward and Greg Reichman" },
  { file: "image1080" },
  { file: "image937" },
  { file: "image391", title: "Wally Hatward" },
  { file: "image621" },
  { file: "image864" },
  { file: "image635" },
  { file: "image386", title: "Wayne Gates" },
  { file: "image288", title: "Richard Rufus Ellis, Graham Doubell and Michael Hunter Smith" },
  { file: "image939", title: "Showgirls. Richard Rufus Ellis, Graham Doubell and Craig Peetz" },
  { file: "image766-2", title: "Richard Rufus Ellis" },
  { file: "image51", title: "Marjorie Chase's Ice Skating showgirls. Richard Rufus Ellis" },
  { file: "image1047", title: "Adi Coetzee and Neil Dundas" },
  { file: "image262", title: "Lawrence Potgieter" },
  { file: "image357", title: "Eddy Palland" },
  { file: "image583", title: "Garth Falkner" },
  { file: "image471", title: "Brian Hirst, Dudley Manicom, Anthony Harris, Jeremy Taylor and Horst" },
  { file: "image533-2", title: "Murray Scannell" },
  { file: "image1117", title: "Murray Scanell" },
  { file: "image750", title: "Jeremy Taylor" },
  { file: "image408", title: "Graham Doubell" },
  { file: "image144", title: "Neil Dundas" },
  { file: "image451", title: "Graham Doubell" },
  { file: "image1052", title: "Wayne Saville and Derek Butler" },
  { file: "image684", title: "Cindy West" },
  { file: "image653", title: "Lauren Shipton" },
  { file: "image152", title: "Henry Davies in Paris" },
  { file: "image842", title: "Patrick Brill at The Landdrost Hotel, Johannesburg" },
  { file: "image102", title: "Henry Davies and Illana Woolfe at her school dance" },
  { file: "image406", title: "Stephen Pritchard in Johannesburg" },
  { file: "image108", title: "Greg Reichman in Johannesburg" },
  { file: "image771", title: "Greg Reichman" },
  { file: "image649", title: "Peet Coetzee and Alan Whitehead" },
  { file: "image1166", title: "Peet Coetzee" },
  { file: "image362", title: "Peet Coetzee and Alan Whitehead" },
  { file: "image942", title: "White Party outside the Zodiac. Linda Basson, Marcel Wishura, Henry Davies, Lianne Basson, Alex Botha and Kerry Bennett" },
  { file: "image747", title: "Alex Botha, Linda Basson, Marcel Wishura, Lianne Basson, Henry Davies and Kerry Bennett" },
  { file: "image622", title: "Kerry Bennett, Henry Davies, Alex Botha, Lianne Basson and Patrick Brill" },
  { file: "image527-2", title: "Leanne, Patrick and Henri in the Berg" },
  { file: "image805", title: "Linda Basson, Marcel Wishura, Leanne Basson and Henry Davies in the Berg" },
  { file: "image438", title: "Henry Davies, Leanne Basson, Marcel Wishura and Linda Basson in the Berg" },
  { file: "image448", title: "Patrick Brill, Henry Davies, Linda Basson and Marcel Wishura camping in the Berg" },
  { file: "image881", title: "Patrick Brill at Chelsea Studios, Chelsea, London" },
  { file: "image501", title: "Henry Davies in London" },
  { file: "image252", title: "Cheryl Johnson, Sharon Coetsee, Louis de Araujo, Henry Davies, Stephen Pritchard and Kerry Bennett" },
  { file: "image401", title: "Henry Davies and Patrick Brill at the Cinzano Design Competition that Patrick won." },
  { file: "image647", title: "Durban Train Station Workshops shoot. Chantal de Vries and Henry Davies" },
];

export const EIGHTIES = [
  { file: "image890", title: "Henri, Alan Morrison" },
  { file: "image518", title: "David Goudge" },
  { file: "image392", title: "David, Kerry, Patrick and Henri" },
  { file: "image171", title: "Kevin Botha, Graham Moore, Steven and Peter Moffat" },
  { file: "image528", title: "Cheryl Johnson, David Davies and Henri modelling Andrew Verster's costumes for A Midsummer Night's Dream" },
  { file: "image764", title: "Rehearsal for a show. Steven Lawrences, Dale Shultz, Gary Halfpenny, Kerry, Henri, Gail Butler and Laurel" },
  { file: "image670", title: "Henri Davies" },
  { file: "image606", title: "Lauren and Steven in LA" },
  { file: "image168", title: "Steven in LA" },
  { file: "image84", title: "Steven and Chi Chi La Rue in LA" },
  { file: "image672", title: "Steven in LA" },
  { file: "image54", title: "Lauren and Tom Collins" },
  { file: "image346", title: "Mooi River Textiles Design comp. Stephen Pritchard, Nicola Pritchard and Henry Davies" },
  { file: "image154", title: "Nicola Pritchard, Henry Davies, Carolyn and Stephen Pritchard" },
  { file: "image810", title: "Kim Pru, Nicola Pritchard, Carolyn, Stephen Pritchard and Adele Shandel" },
  { file: "image647", title: "Patrick Brill and Henry Davies at Houghton Mansions, Johannesburg" },
  { file: "image907", title: "Louis de Araujo, Henry Davies and Sophie the poodle" },
  { file: "image650", title: "Garth Gething on a weekend down the South Coast" },
  { file: "image81", title: "Stephen Pritchard down the South Coast" },
  { file: "image447", title: "Henry Davies" },
  { file: "image552", title: "Stephen Pritchard" },
  { file: "image581", title: "Garth Gething" },
  { file: "image112", title: "Mark Dingley, Steven Roche and Tom. A weekend at Granny's Cottage, Ballito Bay, North Coast, Natal" },
  { file: "image265", title: "Patrick Brill, Tom, Rene Kent, Steven Roche, Ian Perry, Mark Dingley & Garth Gething" },
  { file: "image335", title: "Henry Davies, Richard Rufus Ellis, Ian Perry, Rene Kent, Steven Roche and Ricky" },
  { file: "image333", title: "Ian Perry, Steven Roche, Ricky, Richard Rufus Ellis, Rene Kent & Henry Davies" },
  { file: "image645", title: "Rene Kent" },
  { file: "image311", title: "Steven Roche and Rene Kent" },
  { file: "image329", title: "Rene Kent" },
  { file: "image605", title: "Rene Kent doing Miss Subway" },
  { file: "image94", title: "Rene Kent" },
  { file: "image715", title: "Richard Rufus Ellis and Tom" },
  { file: "image870", title: "Ian Perry, Richard Rufus Ellis, Steven Roche and Patrick Brill" },
  { file: "image824", title: "Steven Roche aka The Pennay, Mark Griffin and Mathew Kelly at the GAZA Ball, Johannesburg" },
  { file: "image716", title: "Alan Froneman and Louis de Araujo at the GAZA Ball, Johannesburg" },
  { file: "image430", title: "Mark Griffin" },
  { file: "image679", title: "Steven Roche and Mark Griffin" },
  { file: "image904", title: "Spencer Pillay, Mark Griffin and Neil Starr" },
  { file: "image922", title: "Henry Davies, Steven Roche and Patrick Brill at The Gasa Ball" },
  { file: "image59", title: "Alan Froneman aka Alice and Mathew Kelly" },
  { file: "image337", title: "Steven Roche, Mark Griffin and Mathew Kelly" },
  { file: "image446", title: "Mark Griffin" },
  { file: "image738", title: "David Goudge" },
  { file: "image340", title: "David Goudge" },
  { file: "image557", title: "Garth Gething" },
  { file: "image291", title: "Karen Hollister's 21st birthday party. Mark Dingley, Karen Hollister and Gary Halfpenny" },
  { file: "image375", title: "Henry Davies and Miguel at Karen Hollister's 21st Birthday" },
  { file: "image704", title: "Rene Kent and Henry Davies" },
  { file: "image1159", title: "Garth Gething, Rod Gallagher and Henri Davies" },
  { file: "image517", title: "Steven Roche and Jackie Bryant" },
  { file: "image748", title: "Gavin Woolfe and Louis de Araujo" },
  { file: "image513", title: "Alfie Saville and Henry Davies at HD Menswear store, Salisbury Arcade, Durban" },
  { file: "image767", title: "Mirco Broggian at HD Menswear" },
  { file: "image221", title: "Graham Simpson and Henry Davies" },
  { file: "image816", title: "Garth Gething and Tamar Marqaud" },
  { file: "image576", title: "Adele Shandel" },
  { file: "image163", title: "Kerry Bennett Fashion Show Liz Staniford, Cheryl Johhnson & Kerry Bennett" },
  { file: "image135", title: "Henry Davies and Dudu Mkhize" },
  { file: "image218", title: "David Goudge" },
  { file: "image65", title: "A day at Salt Rock Beach Steven and Ian" },
  { file: "image436", title: "Patrick" },
  { file: "image175", title: "Henri and Rene" },
  { file: "image812", title: "Duncan and Liz Good" },
  { file: "image928", title: "Ian, Henri and Patrick" },
  { file: "image169", title: "Rene" },
  { file: "image1109", title: "Henry Davies and Derek Lavarak at the Grahamstown monument" },
  { file: "image196", title: "Patrick in Cape Town" },
  { file: "image555", title: "Murray Scannell and Patrick" },
  { file: "image440", title: "Cape Town drag party Lynton Lefevre, Patrick and Maxi Spazzoli" },
  { file: "image9", title: "Lynton and Patrick" },
  { file: "image865", title: "A weekend down the South Coast Mark Dingley, Henri, Wayne Kobusch and Noel Osborne" },
  { file: "image482", title: "Cape Town road trip Henri, Gary Halfpenny and Mark" },
  { file: "image803", title: "Mark, Gary and Henri" },
  { file: "image216", title: "Medieval Dinner Party, Albion Road, Rondebosch, Cape Town Patrick, Maxi and Henri" },
  { file: "image28", title: "Stephen Doubell and Maxi" },
  { file: "image67", title: "Murray, Jeneanne, Henri, Ian Swan, Maxi, Patrick and Myra" },
  { file: "image194" },
  { file: "image896", title: "Patrick, Janet Dobey, Henry , Myra Cowell and Murray" },
  { file: "image13", title: "Adele's 21st birthday, Cape Town. Stephen, Adele, Henri, Carolyn and Patrick" },
  { file: "image699", title: "Jenny Bear, Carolyn, Marcel and Adele" },
  { file: "image872", title: "Lauren" },
  { file: "image593", title: "Steven Roche" },
  { file: "image393", title: "Cheryl and Patrick in Le Chic, Durban" },
  { file: "image776", title: "Garth and Patrick" },
  { file: "image455", title: "Patrick, Cheryl and Henri" },
  { file: "image461", title: "David" },
  { file: "image846", title: "Patrick and Garth" },
  { file: "image801", title: "Gail Butler in Parrot fashion" },
  { file: "image75", title: "Parrot, Durban" },
  { file: "image221-2", title: "Henri and Bryan Brett at The Cinzano Design competition" },
  { file: "image579", title: "Rafe Brown and Albert Eloff at the Cinzano Design competition" },
  { file: "image301", title: "Lauren and Grace Jones" },
  { file: "image845", title: "Patrick, Kerry and Neville in Gillian's flat" },
  { file: "image273", title: "x, Spencer, Rene and Lauren" },
  { file: "image640", title: "Mark's birthday at Le Chic. Mark Dingley" },
  { file: "image101", title: "Mark Dingley" },
  { file: "image489", title: "Patrick Brill and Greg" },
  { file: "image856", title: "Karen Ward and Steven Roche" },
  { file: "image744", title: "Patrick, Maxi, Kerry, x and Garth" },
  { file: "image569", title: "Kerry Bennett" },
  { file: "image26", title: "David Goudge" },
  { file: "image428", title: "David Goudge, Kerry Bennett, Patrick Brill and Henri Davies" },
  { file: "image316", title: "Lauren, Henri and Dale Schultz" },
  { file: "image434", title: "Dale, Henri and Lauren" },
  { file: "image61", title: "Lauren, Dale and Henri" },
  { file: "image897", title: "Henri" },
  { file: "image3", title: "Henri and Lauren" },
  { file: "image373", title: "Lauren, Henri and Dale" },
  { file: "image306", title: "Lauren and Henri" },
  { file: "image164", title: "Patrick" },
  { file: "image511", title: "Peter Wasp and Greg Reichman" },
  { file: "image159", title: "Greg Reichman" },
  { file: "image126", title: "Jean de Cruz and Greg Reichman roller skating" },
  { file: "image1180", title: "Jean de Cruz" },
  { file: "image54-2", title: "Greg Reichman" },
  { file: "image302", title: "Greg Reichman" },
  { file: "image1103", title: "Greg Reichman" },
  { file: "image609", title: "Mark Griffin" },
  { file: "image388", title: "Greg Reichman, Nei, Johann and Mark Griffin" },
  { file: "image358", title: "Eddy Palland, Neil, Johann and Mark Griffin" },
  { file: "image309", title: "Peter" },
  { file: "image124", title: "Michael" },
  { file: "image327", title: "Christmas at Ians. Ian" },
  { file: "image322", title: "Stephen" },
  { file: "image921", title: "Rene" },
  { file: "image146", title: "Gillian, Mark and Rene" },
  { file: "image421", title: "Steven" },
  { file: "image58", title: "Gillian and Stephen" },
  { file: "image864", title: "Garth" },
  { file: "image703", title: "Musgrave Mansions, Musgrave Road, Berea, Durban" },
  { file: "image165", title: "Henry at Musgrave Mansions" },
  { file: "image810-2", title: "Ronnyz" },
  { file: "image603", title: "Kerry, Henry, Maxi and Patrick" },
  { file: "image708", title: "Neville Ward's 50's party Henri, Barbara Lindsey, Kerry, Maxi and Patrick" },
  { file: "image1177", title: "Patrick Brill" },
  { file: "image294", title: "Maxi Spazzoli and Kerry Bennett" },
  { file: "image1046", title: "Kerry Bennett and Patrick Brill" },
  { file: "image437", title: "Maxi Spazzoli" },
  { file: "image387", title: "Barbara Lindsey" },
  { file: "image184", title: "Patrick Brill" },
  { file: "image583", title: "Alexander Manbsions, Essenwood Road, Berea, Durban" },
  { file: "image6", title: "Henri and Casper" },
  { file: "image404", title: "Henri's dining room with Casper at Alexander Mansions" },
  { file: "image491", title: "Henri's 30th birthday party, Alexander Mansions, Durban Leigh Downing, Henri, Rene and Kerry" },
  { file: "image182", title: "Steven, Henri and Mark" },
  { file: "image161", title: "Gary, Henri, Mark and Garth" },
  { file: "image143", title: "Peter, Glenda, Rene, Leigh and Steven" },
  { file: "image793", title: "330 Nightclub, Point Road, Durban" },
  { file: "image537", title: "Penny Rey, Sandra and Terry Scott" },
  { file: "image238", title: "Art Deco relaunch Elsa Pretorius, Eddy de Lima, Henri, Leigh, Cecil Sagorin and x" },
  { file: "image754", title: "Barbara Lindsey's leaving party at Bilbo Daniel, Karl, Suzie, Peter Shanley, Gail Butler, Kerry Bennett, Henry Davies and Dudu Mkhize" },
  { file: "image278", title: "Daniel, Karl, Suzie, Peter Shanley, Gail Butler Kerry Bennett, Henry Davies and Dudu Mkhize" },
  { file: "image1021", title: "Mark Griffin" },
  { file: "image677", title: "Mark Griffin" },
  { file: "image85", title: "Peter Cole and Hilton Davis" },
  { file: "image1167", title: "Peter Moffatt, Graham Moore and Horst" },
  { file: "image360", title: "LA" },
  { file: "image53", title: "Lauren, Jeffery Sanker and x" },
  { file: "image63", title: "x, Lauren and Steven, LA" },
  { file: "image507", title: "Henri's birthday dinner. Sally, Lauren and Steven" },
  { file: "image134", title: "Ian, Henri and Patrick" },
  { file: "image12" },
  { file: "image710", title: "Henri and Ian" },
  { file: "image754-2", title: "Lauren and Patrick" },
  { file: "image625", title: "Lawrence Potgieter" },
  { file: "image385", title: "Lawrence Potgieter" },
  { file: "image681", title: "Michael Hunter Smith" },
  { file: "image144", title: "Duncan and Liz Good's wedding" },
  { file: "image894", title: "Vetchies Pier, Durban Garth and Noel" },
  { file: "image486", title: "David and Bernard" },
  { file: "image634", title: "Jack's farewell drag party. Mark and Patrick" },
  { file: "image342", title: "Jack's farewell drag party. Jack, Bruce, Rene, Ian, Patrick, Steven and Mark" },
  { file: "image56", title: "Henri, Steven, Garth and Mark" },
  { file: "image43", title: "GASA Festival, Durban" },
  { file: "image223", title: "Durban Gay Festival, Frank Melman" },
  { file: "image643", title: "Durban Gay Festival" },
  { file: "image271", title: "GASA Festival" },
  { file: "image186", title: "Gay Students" },
  { file: "image612" },
  { file: "image407" },
  { file: "image383", title: "The judges. Ronnie Botha, Garth Gething" },
  { file: "image756", title: "Hunk compere Penelope Stevens aka Steven" },
  { file: "image503", title: "Steven and hunk" },
  { file: "image136", title: "Hunks" },
  { file: "image852", title: "Steven" },
  { file: "image608", title: "Hunks and Steven" },
  { file: "image808", title: "Hunk competition" },
  { file: "image505", title: "ID3 Fashion Show" },
  { file: "image77", title: "Mark Griffin, Rene" },
  { file: "image514", title: "Cabaret. Mark" },
  { file: "image299", title: "Cabaret" },
  { file: "image435", title: "Mark" },
  { file: "image106", title: "Cabaret. Mark" },
  { file: "image712", title: "Mark" },
  { file: "image190", title: "Mark" },
  { file: "image669", title: "Mark" },
  { file: "image459" },
  { file: "image898", title: "Yazoo staff" },
  { file: "image422", title: "Rene" },
  { file: "image236" },
  { file: "image44" },
  { file: "image711", title: "Peter" },
  { file: "image796", title: "Henri's fashion label launch" },
  { file: "image524", title: "Lauren, Sally and" },
  { file: "image519", title: "Lauren and Steven" },
  { file: "image919", title: "Michael, Trevor and Steven" },
  { file: "image797", title: "Michael, Trevor and Steven" },
  { file: "image449", title: "Greg Reichman and Mark" },
  { file: "image780", title: "Steven, Rene, Mark" },
  { file: "image1093", title: "Louis de Araujo, Neil Starr and Michael van Rensburg" },
  { file: "image484", title: "Gillian wearing Henri Davies" },
  { file: "image751", title: "Gillian wearing Henri Davies" },
  { file: "image520", title: "Ian in the Glamorous Granny competition" },
  { file: "image405", title: "Peter White in Glamorous Granny" },
  { file: "image546", title: "Ian the winner of Glamorous Granny" },
  { file: "image167", title: "Michael" },
  { file: "image89", title: "Michael" },
  { file: "image596", title: "Cecil Lyons, Alan and Michael" },
  { file: "image795", title: "Michael" },
  { file: "image15", title: "SAA flying crew. Michael and Phillip Schaffer" },
  { file: "image549", title: "MIchael" },
  { file: "image267", title: "Michael" },
  { file: "image631" },
  { file: "image612-2", title: "Six of the Best Fashion show, Elangeni Hotel, Durban. Henry Davies" },
  { file: "image613", title: "Johan" },
  { file: "image402", title: "Steven, Neil and x" },
  { file: "image305", title: "Mark" },
  { file: "image350", title: "Michael at Blaauwbergstrand" },
  { file: "image822", title: "Phillip, Butch Loggenberg and Greg Reichman" },
  { file: "image59-2", title: "Butch Loggenberg and Phillip" },
  { file: "image835", title: "x, Neil Dundas and Steven" },
  { file: "image124-2", title: "Lauren and Ian" },
  { file: "image1028", title: "Sandy Bay. Henry Davies, Stephen Pritchard and Bernard Hatch" },
  { file: "image1113", title: "Sandy Bay. Henry Davies" },
  { file: "image196-2", title: "The Cape. Henry Davies" },
  { file: "image687", title: "Seapoint Pool, Cape Town. Henry Davies" },
  { file: "image657", title: "Lanzerac Hotel, Stellenbosch, Cape. Kim Prue, Stephen Pritchard, Henry Davies and Derek Lavarak" },
  { file: "image1045", title: "Stephen Pritchard and Henry Davies" },
  { file: "image635", title: "Gillian, Lee Fine and Ian" },
  { file: "image145" },
  { file: "image629", title: "Spencer and Mark" },
  { file: "image763", title: "Spencer and Mark" },
  { file: "image798", title: "Spencer" },
  { file: "image187", title: "ID Card. Henry Davies" },
  { file: "image253", title: "Winning the Alley Cat Design Competition. David Ross, Chris Levin, Elsie Davies, Henry Davies, Dale Shultz and Cristina" },
  { file: "image482-2", title: "Dale Shultz, Henry Davies, Lianne Basson, Fred Prior, Kerry Bennett, Cheryl Johnson and Yule" },
  { file: "image396", title: "Leigh Downing's 10th anniversary, Squire Loft, Florida Road, Durban" },
  { file: "image1090", title: "Eddie de Lima, Mark, Garth and Tanya at Fiamma Forsdick's restaurant Napier Street, Cape Town" },
  { file: "image830", title: "Gael Butler" },
  { file: "image783", title: "Rene Kent" },
  { file: "image656", title: "Neil Starr" },
  { file: "image591", title: "Mark Griffin" },
  { file: "image535", title: "Rene Kent" },
  { file: "image718", title: "The Riviera Bar, Esplanade, Durban" },
  { file: "image225", title: "Graham Doubell, Brian Haddock, Karen Ward and Neil Dundas" },
  { file: "image266", title: "Alwyn, Arthur Garrod and Jackie Bryant" },
  { file: "image721", title: "Brian Haddock" },
  { file: "image417", title: "Derek Butler" },
  { file: "image756-2", title: "Phillip Lee and Rene Kent" },
  { file: "image343", title: "Philip Lee" },
  { file: "image948", title: "Greg Reichman" },
  { file: "image1100", title: "Graham Moore and Greg Reichman" },
  { file: "image199", title: "John and Graham Moore" },
  { file: "image791", title: "Greg Reichman" },
  { file: "image1112", title: "Phillip and Greg Reichman, Sydney, Australia" },
  { file: "image380", title: "Mark Griffin" },
  { file: "image675", title: "Mark Griffin" },
  { file: "image729", title: "Mark Griffin" },
  { file: "image411", title: "Mark Griffin" },
  { file: "image69", title: "Lauren Shipton and Tom Collins" },
  { file: "image603-2", title: "Rocky Farren" },
  { file: "image325", title: "Graham Moore and Peter Wasp" },
  { file: "image198", title: "Alan Whitehead" },
  { file: "image401", title: "Brian Haddock" },
  { file: "image191", title: "Wayne Gates" },
  { file: "image508", title: "Michael van Rensburg" },
  { file: "image677-2", title: "Seyton Machattie and Leonardo Lupini" },
  { file: "image515", title: "Richard Rufus Ellis and Michael Mc Cann" },
  { file: "image166", title: "Richard Rufus Ellis, Michael Mc Cann and Alfie Bosman" },
  { file: "image79", title: "Neville Letard" },
  { file: "image775" },
  { file: "image266-2", title: "Gillian Lenton" },
  { file: "image536", title: "Mark Griffin" },
  { file: "image45", title: "The Durban July Handicap. Leigh Downing, Henry Davies and Jenny Jarvis" },
  { file: "image748-2", title: "Leigh Downing" },
  { file: "image515-2", title: "Mark Griffin and Lauren Shipton in LA" },
  { file: "image772", title: "Mark Griffin and Lauren Shipton" },
  { file: "image85-2", title: "Lauren Shipton" },
  { file: "image397", title: "Louis de Araujo and Michael van Rensburg in Portugal" },
  { file: "image184-2", title: "Michael van Rensburg and his sisters" },
  { file: "image809", title: "Louis de Araujo at Madame Tussauds" },
  { file: "image225-2", title: "Mark Griffin in LA" },
  { file: "image800", title: "Mark Griffin" },
  { file: "image698", title: "Mark Griffin and Herb Klein" },
  { file: "image499", title: "Mark Griffin and Herb Klein" },
  { file: "image119", title: "Graham Doubell, Neil Dundas and Karen Ward" },
  { file: "image781", title: "Louis de Araujo and Sophie" },
  { file: "image500", title: "Mathew Kelly" },
  { file: "image889", title: "Mark Griffin" },
  { file: "image883", title: "Mathew Kelly" },
  { file: "image71", title: "Tanya van Agthoven and Henry Davies doing make up pre Fashion show" },
  { file: "image664", title: "Steven Roche, Michael van Rensburg and Arthur" },
  { file: "image188", title: "Richard Rufus Ellis, Andre Naude and Michael Mc Cann" },
  { file: "image1043", title: "Murray Scannell and Michael Mc Cann" },
  { file: "image1155", title: "Brian Louis" },
  { file: "image624", title: "Rene Kent as Miss Subway" },
  { file: "image726", title: "Mark Griffin" },
  { file: "image246", title: "Gillian Lenton" },
  { file: "image147", title: "Treva Norris, Steven Roche and Neil Dundas" },
  { file: "image730", title: "Seyton Machattie, Mark Griffin and Spencer Pillay" },
  { file: "image382", title: "Mark Griffin" },
  { file: "image1089", title: "Mark Griffin, Spencer Pillay and Seyton Machattie" },
  { file: "image137", title: "Peter Moffatt and Steven Roche aka The Pennay" },
  { file: "image880", title: "Mark Griffin" },
  { file: "image183", title: "Mark Griffin" },
  { file: "image219", title: "French Tea Party at Albion Road, Rondebosch, Cape Town. Patrick Brill, Peter Harris and Murray Scannell" },
  { file: "image125", title: "Arabian Nights party, London. Maxi Spazzoli and Patrick Brill" },
  { file: "image177", title: "Patrick Brill" },
  { file: "image38", title: "Mark Griffin" },
  { file: "image712-2", title: "Mark Griffin" },
  { file: "image569-2", title: "Mark Griffin" },
  { file: "image315", title: "Mark Griffin" },
  { file: "image381", title: "Mark Griffin" },
  { file: "image324", title: "Mark Griffin and Gavin Woolfe aka The Weep at Mark's birthday party" },
  { file: "image620", title: "Seyton Machattie and Mark Griffin" },
  { file: "image538", title: "Mark's Birthday. Gavin Woolfe and Mark Griffin" },
  { file: "image802", title: "Mark Griffin, Gillian Lenton and Seyton Machattie" },
  { file: "image19", title: "Mathew Kelly and Louis de Araujo" },
  { file: "image1035", title: "Mark Griffin" },
  { file: "image105", title: "Arthur and Michael Hunter Smith" },
  { file: "image879", title: "Mark Griffin and Spencer Pillay" },
  { file: "image1", title: "Gillian Lenton and Mark Griffin" },
  { file: "image746", title: "Mark Griffin" },
  { file: "image855", title: "Liz Staniford and Andries Botha's wedding invite" },
  { file: "image305-2", title: "Michael Hunter Smith" },
  { file: "image667", title: "Patrick Brill and model" },
  { file: "image566", title: "Noel Osborne, Stephen Pritchard, Patrick Brill, Henry Davies, Derek Lavarack and Alan Watt" },
  { file: "image560", title: "Stephen Pritchard and Bernard Hatch" },
  { file: "image742", title: "Mark Griffin" },
  { file: "image823", title: "Peter Cole" },
  { file: "image504", title: "Hilton Davis and Peter Cole" },
  { file: "image921-2", title: "Peter Cole" },
  { file: "image853", title: "Neil Starr and Henry Davies" },
  { file: "image303", title: "Neil Dundas" },
  { file: "image339", title: "Neil Dundas, Karen Ward and Adi Coetzee" },
  { file: "image431", title: "Rene Kent, Peter Moffatt and Steven Roche" },
  { file: "image11", title: "Gavin Woolfe and Jackie Woolfe" },
  { file: "image945", title: "Granny Lee" },
  { file: "image1104", title: "Steven Roche" },
  { file: "image859", title: "Peter Cole" },
  { file: "image2", title: "Noel van Wildenrath and Rene Kent" },
  { file: "image371", title: "Mark Griffin" },
  { file: "image23", title: "Patrick Brill, Christine Popoff, Anina Cummings, Mark and Kerry Bennett at a 50's party." },
  { file: "image451", title: "Patrick Brill, Glenda Holmes and Kevin Halcut" },
  { file: "image141", title: "Patrick Brill, Mark Griffin and Arthur Garrod" },
  { file: "image116", title: "Thelma and Tony" },
  { file: "image424", title: "Eddie de Lima and Tanya van Agthoven" },
  { file: "image708-2", title: "Mark Griffin and Arthur Garrod" },
  { file: "image185", title: "Maxi Spazzoli, Patrick Brill and Stephen Doubell in Bantry Bay, Cape Town" },
  { file: "image68", title: "Mark Griffin" },
  { file: "image224", title: "Mark Griffin and Patrick Talmadge aka Doris" },
  { file: "image55", title: "Neil Starr, Patrick Talmadge, Mark Griffin and Spencer Pillay" },
  { file: "image141-2", title: "Mark Griffin and Patrick Talmadge" },
  { file: "image480", title: "Sally Fisher" },
  { file: "image189", title: "Mathew Kelly" },
  { file: "image31", title: "Tanya van Agthoven and Leigh Downing" },
  { file: "image140", title: "Mark Griffin, Jackie Bryant and Spencer Pillay" },
  { file: "image430-2", title: "Mathew Kelly, Mark Griffin, Spencer Pillay and Neil Starr" },
  { file: "image730-2", title: "Mark Griffin" },
  { file: "image739", title: "Mark Griffin" },
  { file: "image151", title: "Jackie Bryant" },
  { file: "image154-2", title: "Mark Griffin and Arthur Garrod" },
  { file: "image486-2", title: "Mark Griffin" },
  { file: "image378", title: "Louis de Araujo at Henry's Venice Road cottage, Durban" },
  { file: "image257", title: "Patrick Brill, Louis de Araujo and Henry Davies" },
  { file: "image477", title: "Adi Coetzee and Gillian Lenton" },
  { file: "image779", title: "Henry Davies at The Castle in the Transvaal" },
  { file: "image492", title: "Steven Roche" },
  { file: "image135-2", title: "Garth Gething and Patrick Brill" },
  { file: "image720", title: "Louis de Araujo" },
  { file: "image460", title: "Gillian Lenton and Steven Roche" },
  { file: "image198-2", title: "Gillian Lenton and Lauren Shipton" },
  { file: "image474", title: "Steven Roche at Derek Meuvis's pool" },
  { file: "image279", title: "Kerry Bennett, Gillian Lenton and Heather Roche" },
  { file: "image688", title: "Rene's invite. Rene Kent" },
  { file: "image276", title: "Treva Norris" },
  { file: "image1057", title: "Hilton Davis and Peter Cole aka Chunky and Lulu" },
  { file: "image1121", title: "Peter Cole aka Lulu" },
  { file: "image557-2", title: "Mark Griffin" },
  { file: "image822-2", title: "Steven Roche" },
  { file: "image614", title: "Steven Roche at Zipps club, Johannesburg" },
  { file: "image541", title: "Steven Roche" },
  { file: "image648", title: "Best Dressed Men. Henry Davies" },
  { file: "image666", title: "Mark Griffin" },
  { file: "image478", title: "Treva Norris" },
  { file: "image410", title: "Treva Norris and Michael Hunter Smith" },
  { file: "image792" },
  { file: "image707", title: "Treva Norris, Michael Hunter Smith and Mark Griffin" },
  { file: "image286", title: "Louis Christmas Card. Louis de Araujo" },
  { file: "image418", title: "Lauren modelling in LA. Lauren Shipton" },
  { file: "image187-2", title: "Mark Griffin and Steven Roche in Amanzimtoti" },
];

export const NINETIES = [
  { file: "image304", title: "Garth Gething and Henry Davies in Durban" },
  { file: "image278", title: "Colin Mc Gree and Patrick Brill" },
  { file: "image821", title: "Joan Johnson and her son at her graduation" },
  { file: "image892", title: "Garth Gething and Henry Davies" },
  { file: "image420", title: "Louis de Araujo and Jessie in Vancouver, Canada" },
  { file: "image173", title: "Mark Lowe" },
  { file: "image463", title: "Michael Hunter Smith, Patrick Brill and Rene Kent" },
  { file: "image594", title: "Seyton Machattie and Arthur" },
  { file: "image636", title: "Arthur and Stephane" },
  { file: "image171", title: "Kevin Mac Innes, Graham Moore, Steven Roche, Richard Yell and Peter Moffatt" },
  { file: "image431", title: "Henri photographed by George Ktistakis in Spitalfields, London Henry Davies" },
  { file: "image70", title: "Steven Roche" },
  { file: "image398", title: "Steven Roche and Jackie Bryant" },
  { file: "image849", title: "Seyton Machattie" },
  { file: "image561", title: "Seyton Machattie and Steven Roche" },
  { file: "image105", title: "Henry Davies and Jonathan Arun, Wesyt Hampstead, London" },
  { file: "image814", title: "Steven Roche, Henry Davies and Garth Gething at Garth's party in Durban" },
  { file: "image657", title: "Garth Gething, Gary Searle, Garth Marquard and Boyd Ferguson" },
  { file: "image429", title: "David Ralphs, Peter Wishart and Alfie Bosman" },
  { file: "image86", title: "Henry Davies and Garth Gething" },
  { file: "image789", title: "Henry Davies and Steven Roche" },
  { file: "image466", title: "Michael Hunter Smith" },
  { file: "image250", title: "Michael and Steven" },
  { file: "image445", title: "Steven, Michael and Steven's work colleagues" },
  { file: "image680", title: "Brian Louis" },
  { file: "image275", title: "Neil and Michael" },
  { file: "image644", title: "Ian and Gillian" },
  { file: "image570", title: "Patrick, Carol Doubell, Steven, Adi, Gillian, Sally, Michael and Neil" },
  { file: "image620", title: "Steven, Neil and Gillian" },
  { file: "image227", title: "Steven" },
  { file: "image652", title: "Steven's favourite cafe at Mitchell Park, Durban" },
  { file: "image263", title: "Priscilla Blackie, Penny Brill, Nicola and Megan Blackie, Steven" },
  { file: "image553", title: "Patrick, Johan, Steven, Trevor and Gavin" },
  { file: "image249", title: "Lauren, Henri and Patrick" },
  { file: "image732", title: "Steven and Colin Hutt" },
  { file: "image101", title: "Patrick, Steven, Sally and Michael" },
  { file: "image832", title: "Michael, Patrick, Steven and Kevin MacInnes" },
  { file: "image321", title: "Sally and Steven" },
  { file: "image205", title: "Karen Ward and Richard" },
  { file: "image311", title: "Sally Chance's Birthday party. 330, Durban. Michelle Barfoot, Mark, Deanne Halfon and Sally Chance" },
  { file: "image629", title: "330 Party Mark, Sally Chance, Patrick, Carrie and Carl Isaacs" },
  { file: "image232", title: "Mark, Carrie, Carmen Laurier, and Rafe Brown" },
  { file: "image244", title: "Jenna, Michael, Leonardo and Seyton" },
  { file: "image450", title: "Henri and Barrie in Canterbury" },
  { file: "image671", title: "Rocky Horror Party Patrick, Steven and Kevin Mc Innes" },
  { file: "image874", title: "Michael, Steven and Patrick" },
  { file: "image714", title: "Karen, Steven and Lisa" },
  { file: "image366", title: "Steven" },
  { file: "image214", title: "Steven and Arthur" },
  { file: "image204", title: "Trevor and Steven" },
  { file: "image784", title: "Steven" },
  { file: "image926", title: "Leigh, Heather Roche, Steven and Karen" },
  { file: "image588", title: "Allen and Steven" },
  { file: "image630", title: "Brettlee, Michael and Kevin" },
  { file: "image80", title: "Steven and Patrick" },
  { file: "image701", title: "Carolyn de Beyer, Shaun" },
  { file: "image619", title: "Steven" },
  { file: "image231", title: "Cheryl and Robert Johnson" },
  { file: "image532", title: "Colin Hutt" },
  { file: "image687", title: "Steven and Peter" },
  { file: "image844", title: "Steven and colleagues" },
  { file: "image895", title: "Steven, Sally, Patrick and Michael at MCQP Safari Camp Party 1998" },
  { file: "image113", title: "Jackie and Steven" },
  { file: "image696", title: "Choo, Kevin, Steven, Michael" },
  { file: "image681", title: "Steven and Patrick" },
  { file: "image676", title: "Steven and Patrick" },
  { file: "image93", title: "Adi and Gillian" },
  { file: "image602", title: "Gillian and Lisa Owen" },
  { file: "image138", title: "Neil and Gillian" },
  { file: "image818", title: "Karen, Gillian and Lisa" },
  { file: "image745", title: "Gillian, Neil and Spencer" },
  { file: "image813", title: "Sally and Steven" },
  { file: "image132", title: "Patrick and Jenna" },
  { file: "image655", title: "Patrick" },
  { file: "image139", title: "Steven" },
  { file: "image530", title: "Steven, Gillian and Michael" },
  { file: "image426", title: "Sally, Jenna, Michael and Neil" },
  { file: "image633", title: "Breda and Michael Crouch" },
  { file: "image534", title: "Kevin, Sally andPatrick" },
  { file: "image191", title: "Steven, Michael, Kevin and Patrick" },
  { file: "image717", title: "Kevin and Steven" },
  { file: "image691", title: "Michael" },
  { file: "image367", title: "Henri and Lauren, LA, California" },
  { file: "image599", title: "Lauren and Peter Amsden, Laurel Canyon, LA" },
  { file: "image39", title: "Seaton and Leonardo" },
  { file: "image901", title: "Steven, Sally and Patrick" },
  { file: "image722", title: "Louis in San Fransisco" },
  { file: "image628", title: "Louis in New York" },
  { file: "image468", title: "Michael" },
  { file: "image765", title: "Alan Whitehead and Choo" },
  { file: "image680-2", title: "Michael" },
  { file: "image390", title: "Michael and Patrick" },
  { file: "image103", title: "Jenna, Sally and Steven" },
  { file: "image119", title: "Sally" },
  { file: "image42", title: "Neil, Sally, Patrick and Michael" },
  { file: "image621", title: "Steven, Michael, Kevin McInnes and Patrick" },
  { file: "image597", title: "Colin, Douglas, Michael, Sally, Bretlee, Seaton, Patrick and Steven at The Trossachs, MacGregor" },
  { file: "image268", title: "Michael and Seaton" },
  { file: "image721", title: "Michael" },
  { file: "image741", title: "Patrick" },
  { file: "image292", title: "Patrick" },
  { file: "image414", title: "Gillian and Michael" },
  { file: "image651", title: "Patrick and Herb Klein" },
  { file: "image625", title: "Leonardo, Francois, Patrick, Seaton, Jenna and Janiece" },
  { file: "image931", title: "Leonardo, Spencer, Michael, Patrick, Francois, Jenna, and Seyton" },
  { file: "image336", title: "Spencer, Seyton and Steven" },
  { file: "image769", title: "Joan, Seyton, Patrick and Brettlee" },
  { file: "image782", title: "Patrick, Brettlee, Neil, Michael and Sally" },
  { file: "image97", title: "Steven and Michael" },
  { file: "image95", title: "Steven and Heather" },
  { file: "image516" },
  { file: "image51", title: "Michael and Seyton" },
  { file: "image66", title: "Douglas" },
  { file: "image471", title: "Lisa, Karen, Sally, Lee and Glenda" },
  { file: "image283", title: "Steven, Frank Melman" },
  { file: "image200", title: "Petal and The Pennay" },
  { file: "image760", title: "Louis" },
  { file: "image700", title: "Louis, Illana and Gavin in Seattle" },
  { file: "image362", title: "Illana, Karen, Patrick and Louis in Seattle" },
  { file: "image313", title: "Patrick" },
  { file: "image479", title: "Patrick and Louis" },
  { file: "image241", title: "Louis" },
  { file: "image255", title: "Gavin, Illana and Louis" },
  { file: "image496", title: "Louis" },
  { file: "image826", title: "Louis and Patrick" },
  { file: "image674", title: "Michael" },
  { file: "image774", title: "Luke Davies, Henri, Neil Farrelly and Barrie Hadfield in London" },
  { file: "image820", title: "Luke, Peter White, Henri and Barrie" },
  { file: "image485", title: "Greg Davies, Henri, Peter and Luke in The Fridge, Brixton London" },
  { file: "image88", title: "Barrie and Henri in The Fridge, Brixton, London" },
  { file: "image409", title: "Henri, Luke and Barrie. Christmas in West Hampstead, London" },
  { file: "image574", title: "Oliver Ellis and Henri at Gay Pride 94 in London" },
  { file: "image854", title: "Henri and Jonathan Arun at Gay Pride" },
  { file: "image2", title: "Noel and Rene" },
  { file: "image76", title: "Noel" },
  { file: "image307", title: "Denise Britz's Show" },
  { file: "image543", title: "Michael's 40th birthday. Michael and Spencer" },
  { file: "image352", title: "Jenna, Tony Gois, Seyton and Rene" },
  { file: "image415", title: "Patrick and Steven" },
  { file: "image34", title: "Neil, Keith Schultz and Sally" },
  { file: "image284", title: "Patrick and Michael at MCQP Twinkly Sea Party 1996" },
  { file: "image595", title: "Patrick and Sally" },
  { file: "image385", title: "Steven and Patrick" },
  { file: "image584", title: "Patrick and Dada" },
  { file: "image17" },
  { file: "image222", title: "Patrick, Kevin and Michael" },
  { file: "image384", title: "Patrick" },
  { file: "image900", title: "Kevin" },
  { file: "image488", title: "Kevin" },
  { file: "image672", title: "Steven" },
  { file: "image568", title: "Steven" },
  { file: "image104" },
  { file: "image899", title: "The Lot Hotel, En Bokek, the Dead Sea, Israel. The site of the original Sodom and the start of my relationship with Barrie." },
  { file: "image345", title: "Henri in the Dead Sea" },
  { file: "image388", title: "Henri" },
  { file: "image296", title: "Barrie" },
  { file: "image188", title: "Barrie, Shlommie and Henri at En Gedi, The Dead Sea, Israel" },
  { file: "image240", title: "Barrie" },
  { file: "image449", title: "Henri on the Bishop's throne, The Church of the Holy Sepulchre, Jerusalem, Israel" },
  { file: "image193", title: "Rene and Karen" },
  { file: "image637", title: "Sally, Steven and Richard" },
  { file: "image649", title: "Henri and Garth, Spitalfields, London" },
  { file: "image387", title: "Luke and Barrie" },
  { file: "image531", title: "Peter Wishart and Garth, Spitalfields, London" },
  { file: "image917", title: "Peter" },
  { file: "image577", title: "Garth and Rafe Brown, Spitalfields, London" },
  { file: "image632", title: "Luke and Henri" },
  { file: "image476", title: "Barrie and Henri" },
  { file: "image417", title: "Onion Ring 20th year reunion. Trevor, Ian, Adi, Peter, Sally, Mrs Roche, Joan, Pam and Karen" },
  { file: "image558", title: "Jenna and Seyton" },
  { file: "image706", title: "Sean Keegan and Peter" },
  { file: "image312", title: "Shaun, Carolyn and Micheal Cheze" },
  { file: "image512", title: "Kevin, Patrick and Steven" },
  { file: "image638", title: "Steven and Colin" },
  { file: "image320", title: "Seaton, Michael and Rene" },
  { file: "image307-2", title: "Steven" },
  { file: "image723", title: "Garth and Todd Barry. Spitalfields, London" },
  { file: "image873", title: "Steven" },
  { file: "image343", title: "Kevin and Steven" },
  { file: "image521", title: "Steven" },
  { file: "image502", title: "Steven and Frank Melman" },
  { file: "image580", title: "Henri and Mark Davis in the DJ booth of Heaven, London" },
  { file: "image170", title: "Mark Davis" },
  { file: "image50", title: "Henri at Mark's flat, Battersea, London" },
  { file: "image609", title: "Steven" },
  { file: "image887", title: "Henri- Trade membership card" },
  { file: "image920", title: "James Moffat and Henri, Spitalfields, London" },
  { file: "image131", title: "James, Barrie and Henri" },
  { file: "image679", title: "Steven" },
  { file: "image838", title: "Steven" },
  { file: "image737", title: "Henri and Mark Cioli, England" },
  { file: "image24", title: "Steven" },
  { file: "image713", title: "Steven and Jenna" },
  { file: "image666", title: "Henri in Cheshire" },
  { file: "image690", title: "Cheryl and Patrick" },
  { file: "image833", title: "Sally and Jenna" },
  { file: "image423", title: "Steven and Patrick" },
  { file: "image259", title: "Arthur, Neil and Michael" },
  { file: "image206", title: "Choo, Alan Whitehead and Colin" },
  { file: "image510", title: "Rowan and Garth" },
  { file: "image157", title: "Steven and Garth" },
  { file: "image207", title: "Mark" },
  { file: "image114", title: "20th Reunion at The Georges 5. Treva, Steven, Jackie, Adi, Sally, Michael and Karen" },
  { file: "image52", title: "Steven compering Mr Axis" },
  { file: "image857", title: "Leigh and Duncan" },
  { file: "image91", title: "Steven" },
  { file: "image82", title: "Gavin and Jackie" },
  { file: "image511", title: "Jackie" },
  { file: "image395", title: "Jackie" },
  { file: "image551", title: "Michael and Louis" },
  { file: "image123", title: "Robbie Pfister and Michael" },
  { file: "image753", title: "Michael" },
  { file: "image248", title: "Jackie and Sally" },
  { file: "image220", title: "June Schmarmen, Leigh and Gillian" },
  { file: "image815", title: "Josef, Adi and Neil" },
  { file: "image424", title: "Steven" },
  { file: "image923", title: "Neil and Michael" },
  { file: "image571", title: "Garth and Henri in Durban" },
  { file: "image494", title: "Peter White's Mother NYE Party" },
  { file: "image542", title: "Nicole, Upstate New York" },
  { file: "image386", title: "Henri" },
  { file: "image727", title: "Henri in Chloe's flat, Egerton Gardens, South Kensington, London" },
  { file: "image794", title: "Henri in New York" },
  { file: "image893", title: "John Truex, New York" },
  { file: "image237", title: "Ian, New York" },
  { file: "image523", title: "Henri, New York" },
  { file: "image14", title: "Gregory Pierrotti, New York" },
  { file: "image724", title: "Henri" },
  { file: "image212", title: "Henri" },
  { file: "image202", title: "Chloe Rolfes and Henri in New York" },
  { file: "image868", title: "Henri working at Kin Khao, New York" },
  { file: "image439", title: "Christine, Henri and Guy, Kin Khao, New York" },
  { file: "image578", title: "Brad" },
  { file: "image791", title: "Henri" },
  { file: "image172", title: "Steven and Patrick" },
  { file: "image368", title: "Henri in Juice, Covent Garden, London" },
  { file: "image453", title: "David Ross" },
  { file: "image303", title: "Juice menu" },
  { file: "image8", title: "Craig" },
  { file: "image444", title: "Barrie and Henri" },
  { file: "image590", title: "First iMac Internet cafe in London" },
  { file: "image19", title: "Juice" },
  { file: "image87", title: "Art Gallery and Internet Cafe at Juice, Covent Garden, London" },
  { file: "image357" },
  { file: "image867", title: "Skweeze Juice Bar, Toronto, Canada" },
  { file: "image906", title: "Skweeze Juice Bar" },
];

export const TWOTHOUSANDS = [
  { file: "image22", title: "Henry Davies and Barrie Hadfield, Marrakesh, Morrocco" },
  { file: "image490", title: "Barrie Hadfield, Henry Davies, Steven Roche and Joan Johnson" },
  { file: "image408", title: "Sally Fisher and Neil Dundas at Garth's pool, Durban" },
  { file: "image361", title: "Douglas, Patrick and Brettlee" },
  { file: "image37", title: "Michael Hunter Smith" },
  { file: "image235", title: "Michael Hunter Smith" },
  { file: "image465", title: "Henry Davies, Mykonos" },
  { file: "image442", title: "Michael Hunter Smith, Patrick Brill and Seyton Machattie" },
  { file: "image554", title: "Patrick Brill, Neil Dundas and Joan Johnson" },
  { file: "image790", title: "Douglas and Chris Weir" },
  { file: "image121", title: "Henry Davies and Barrie Hadfield sailing off Mykonos" },
  { file: "image127", title: "Douglas and Brettlee on their wedding day" },
  { file: "image752", title: "Barrie Hadfield, Marrakesh, Morrocco" },
  { file: "image786", title: "Henry Davies and Barrie Hdafield, Marrakesh, Morrocco" },
  { file: "image425", title: "Michael Hunter Smith, Patrick Brill and Steven Roche" },
  { file: "image686", title: "Henry Davies and Barrie Hadfield at Barrie's 30th birthday, London" },
  { file: "image915", title: "Seyton Machattie" },
  { file: "image472", title: "Seyton Machattie, Leonardo Lupini and Patrick Brill" },
  { file: "image243", title: "Colin Hutt and Patrick Brill" },
  { file: "image641", title: "Brettlee and Patrick" },
  { file: "image598", title: "Douglas and Patrick" },
  { file: "image642", title: "Neil Dundas, Treva Norris, Seyton Machattie, Leonardo Lupini and Patrick Brill" },
  { file: "image280", title: "MIchael and Douglas" },
  { file: "image364", title: "Michael van Rensburg" },
  { file: "image617", title: "Barrie Hadfield, Blackheath, London" },
  { file: "image427", title: "Lauren Shipton, Blackheath, London" },
  { file: "image778", title: "Kevin Mac Innes and Steven Roche" },
  { file: "image18", title: "Graham Moore, Mark, James Moffatt and Peter Moffatt" },
  { file: "image92", title: "Frank Melman and Steven Roche" },
  { file: "image142", title: "Arthur, Treva Norris, Michael Hunter Smith and Seyton Machattie" },
  { file: "image291", title: "Seyton Machattie and Michael Hunter Smith" },
  { file: "image179", title: "Jenna and Seyton Machattie" },
  { file: "image262", title: "Michael van Rensburg" },
  { file: "image888", title: "Henry Davies and Garth Gething at Peter and Graham's house" },
  { file: "image150", title: "Henry Davies" },
  { file: "image504", title: "Mark Dingley" },
  { file: "image663", title: "Henry Davies, Garth `Gething and Rowan" },
  { file: "image859", title: "Darryl Roffey, Kim and Peter White" },
  { file: "image233", title: "Didier Michael Hunter Smith, Steven Roche and Patrick Brill" },
  { file: "image495", title: "Garth's pool" },
  { file: "image10", title: "Henry Davies at Garth's house" },
  { file: "image120", title: "Garth Gething" },
  { file: "image610", title: "Barrie Hadfield and Gordon Seaman" },
  { file: "image929", title: "Barrie and Canadian Gordon Seaman at Peace Cottage" },
  { file: "image522", title: "Barrie Hadfield outside Garth's house, Berea, Durban" },
  { file: "image133", title: "Henry Davies, North Beach, Durban for The Gunston 500" },
  { file: "image695", title: "Barrie Hadfield and Henry Davies sailing" },
  { file: "image905", title: "Jamie and Henry Davies sailing off Mallorca, Spain" },
  { file: "image365", title: "Jamie the most wonderful dog in the world in Mallorca" },
  { file: "image904", title: "Barrie Hadfield, Portals Vells, Mallorca" },
  { file: "image308", title: "Patrick Brill and Neil Dundas" },
  { file: "image863", title: "Cheryl Johnson at Garth's house" },
  { file: "image733", title: "Mark Estagaribia, Lauren Shipton and David Wannamaker, Mallorca" },
  { file: "image825", title: "Mark Estagaribia, Lauren Estagaribia, Henry Davies and Lauren Shipton in Mallorca" },
  { file: "image341", title: "David Wannamaker, Lauren Shipton and Henry Davies, Mallorca" },
  { file: "image118", title: "David Wannamaker, Lauren Estagaribia, Henry Davies, Barrie Hadfield, Lauren Shipton and Ruben Singer, Mallorca" },
  { file: "image851", title: "Ruben Singer, Lauren Estagarribia, Lauren Shipton and Henry Davies sailing off Mallorca" },
  { file: "image160", title: "Patrick Brill and Garth Gething at Garth's house" },
  { file: "image622", title: "Henry Davies in Madurai, India" },
  { file: "image615", title: "Henry Davies, Barrie Hadfield and Jamie sailing in Mallorca" },
  { file: "image351", title: "At home in Blackheath, London. Henry Davies" },
  { file: "image770", title: "Onion Ring 30th Reunion Party. Rowan, Tanya van Agthoven, Leigh Downing and Garth Gething" },
  { file: "image497", title: "Peter Moffatt, Sally Fisher, Gillian Lenton and Karen Ward" },
  { file: "image805", title: "Heather Roche and Mark Dingley" },
  { file: "image247", title: "Rowan, Mark Dingley and Patrick Brill" },
  { file: "image317", title: "Steven Roche, Graham Moore and Peter Moffatt" },
  { file: "image757", title: "Heather Roche and Garth Gething" },
  { file: "image100", title: "Treva Norris and Steven Roche" },
  { file: "image419", title: "Patrick Brill and Carla Thompson" },
  { file: "image886", title: "Mark Lowe and Heather Roche" },
  { file: "image129", title: "Rowan" },
  { file: "image489", title: "Rowan and Debbie Reynolds" },
  { file: "image869", title: "Guy Woods" },
  { file: "image509", title: "Garth Gething, Henry Davies and Leigh Downing" },
  { file: "image811", title: "Guy Woods and Heather Roche" },
  { file: "image96", title: "Sally Fisher, Michael Hunter Smiith, Treva Norris, Steven Roche and Joan Johnson" },
  { file: "image377" },
  { file: "image224", title: "Adi Coetzee, Stephane, Arthur and Michael Hunter Smith" },
  { file: "image158", title: "Steven Roche and Henry Davies" },
  { file: "image572", title: "Barrie Hadfield, Henry Davies, Angel and Cindy West" },
  { file: "image78", title: "Cindy West and Angel" },
  { file: "image20", title: "Henry Davies and Barrie. Hadfield" },
  { file: "image90", title: "Daniel Woolfe, Jenna, Sally Fisher, Neil Dundas, Rowan and Seyton Machattie" },
  { file: "image807", title: "Barrie Hadfield, Henry Davies, Steven Roche, Joan Johnson and Sharon Spradbury" },
  { file: "image318", title: "Garth Gething, Patrick Brill and Henry Davies" },
  { file: "image819", title: "Patrick Brill, Henry Davies and Sally Fiisher at Garth's house" },
  { file: "image153", title: "Garth Gething, Steven Roche and Henry Davies" },
  { file: "image347", title: "Steven Roche and Henry Davies" },
  { file: "image587", title: "Steven Roche, Garth Gething, Patrick Brill, Henry Davies and Jackie Bryant" },
  { file: "image339", title: "Henry Davies and Jamie, St Margaret's Bay" },
  { file: "image540", title: "Patrick Brilland Henry Davies, St Margaret's Bay, Kent, England" },
  { file: "image433", title: "Barrie Hadfield" },
  { file: "image406", title: "Barrie Hadfield and Jamie" },
  { file: "image60", title: "Barrie Hadfield" },
  { file: "image562", title: "St Margaret's Bay, Kent, England" },
  { file: "image761", title: "Jamie and Barrie Hadfield" },
  { file: "image689", title: "Henry Davies and Jamie on the white cliffs at St Margaret's Bay, Kent, England" },
  { file: "image627", title: "Chloe Rolfes and Henry Davies at St Margaret's Bay" },
  { file: "image911", title: "Michael van Rensburg at St Margaret's Bay, Kent, England" },
  { file: "image734", title: "Henry Davies and Chloe Rolfes at Great Dixter, East Sussex, England" },
  { file: "image210", title: "Josef Talotta and Sally Fisher" },
  { file: "image498", title: "Michael Hunter Smith and Seyton Machattie" },
  { file: "image230", title: "Steven Roche" },
  { file: "image538", title: "Steven Roche" },
  { file: "image882", title: "Luke Davies and Henry Davies, Elia Beach, Mykonos" },
  { file: "image174", title: "Steven Roche" },
  { file: "image567", title: "Hayley, Penny Brill, Treva Norris, Steven Roche and Nicola Blackie" },
  { file: "image338", title: "Michael van Rensburg and Patrick Brill" },
  { file: "image452", title: "Arthur and Michael Crouch" },
  { file: "image195", title: "Joan Johnson, Seyton Machattie, Toni Gois and Michael Hunter Smith" },
  { file: "image211", title: "Kevin MacInnes, Steven Roche and Michael Hunter Smith at The Trossachs, Mac Gregor, Cape" },
  { file: "image539", title: "Michael Hunter Smith and Patrick Brill" },
  { file: "image830", title: "Seyton Machattie, Douglas and Michael Hunter Smith" },
  { file: "image891", title: "StevenRoche" },
  { file: "image731", title: "Patrick Brill, Brettlee and Sally Fisher" },
  { file: "image344", title: "Douglas, Sally Fisher and Steven Roche" },
  { file: "image473", title: "Patrick Brill, Brettlee, Douglas, Seyton Machattie, Sally Fisher and Michael Hunter Smith" },
  { file: "image913", title: "Sally Fisher" },
  { file: "image55", title: "Douglas, Seyton Machattie, Steven Roche, Sally Fisher and Michael Hunter Smith" },
  { file: "image547", title: "Colin Hutt, Steven Roche, Seyton Machattie, Patrick Brill, Sally Fisher, Douglas and Brettlee" },
  { file: "image544", title: "Neil Dundas and Michael Crouch" },
  { file: "image319", title: "Michael Hunter Smith and Sally Fisher" },
  { file: "image601", title: "Jenna, Sally Fisher and Steven Roche" },
  { file: "image750", title: "Brettlee, Douglas, Jayshree and Patrick Brill" },
  { file: "image847", title: "Joan Johnson, Priscilla Blackie and Penny Brill" },
  { file: "image208", title: "Sally Fisher, Jenna, Michael Hunter Smith and Neil Dundas" },
  { file: "image197", title: "Brettlee" },
  { file: "image389", title: "Brettlee and Douglas" },
  { file: "image325", title: "Francois, Brettlee, Sally Fisher, Kevin MacInnes and Spiro" },
  { file: "image817", title: "Michael Hunter Smith" },
  { file: "image582", title: "Steven Roche, Sally Fisher, Kevin MacInnes, Neil Dundas and Michael Hunter Smith" },
  { file: "image234", title: "Patrick Brill, Steven Roche and Sally Fisher in MacGregor" },
  { file: "image692", title: "Kevin MacInnes and Colin Hutt" },
  { file: "image799", title: "Barrie Hadfield and Henry Davies get married, Canterbury, Kent, England" },
  { file: "image159", title: "Patrick Brill" },
  { file: "image837", title: "HenrY Davies and Patrick Brill, Mallorca" },
  { file: "image62", title: "Patrick Brill, Henry Davies and Barrie Hadfield in the famous lamb restaurant at the top of the mountain in Mallorca" },
  { file: "image548", title: "Henry Davies and Patrick Brill at C'an Petra Marche in Deia, Mallorca" },
  { file: "image300", title: "Patrick Brill and Henry Davies, Mallorca" },
  { file: "image323", title: "Peter White, Mallorca" },
  { file: "image148", title: "Peter White, Mallorca" },
  { file: "image64", title: "Mallorca pool" },
  { file: "image525", title: "Lauren Shipton and Henry Davies sailing Tyger" },
  { file: "image600", title: "Lauren Shipton at old military base, Mallorca" },
  { file: "image376", title: "Lauren Shipton and super yacht, Mallorca" },
  { file: "image464", title: "Megan de Beyer and Henry Davies, Mallorca" },
  { file: "image735", title: "Henry Davies and Barrie Hadfield, Sydney Australia" },
  { file: "image48", title: "Colin Hutt, Seyton Machattie, Patrick Brill, Treva Norris, Sally Fisher, Nicky and Karen Hollister" },
  { file: "image749", title: "Cheryl Johnson and her cat" },
  { file: "image227", title: "Henry Davies, Graham Moore and Peter Moffatt" },
  { file: "image702", title: "Kevin MacInnes, and Seyton Machattie" },
  { file: "image633", title: "Lynton Lefevre" },
  { file: "image507", title: "Mark Dingley" },
  { file: "image463", title: "Bruce Walsh" },
  { file: "image399", title: "Bruce Walsh" },
  { file: "image1063", title: "Neil Dundas" },
  { file: "image567-2", title: "Neil Dundas" },
  { file: "image21", title: "Kevin MacInnes" },
  { file: "image217", title: "Kevin MacInnes and Seyton Machattie" },
  { file: "image896", title: "Richard Rufus Ellis and Neville Letard" },
  { file: "image872", title: "Neil Dundas, Gillian Lenton and Joan Johnson" },
  { file: "image626", title: "Michael Hunter Smith, Seyton Machattie and Noel van Wildenrath" },
  { file: "image714", title: "Louis de Araujo visits Mallorca. Barrie Hadfield and Henri Davies" },
  { file: "image1058", title: "Mallorca. Henri Davies" },
  { file: "image475", title: "Mallorca. Barrie Hadfield" },
  { file: "image336", title: "Louis in Mallorca. Louis de Araujo" },
  { file: "image89", title: "Henri Davies" },
  { file: "image371", title: "Barrie Hadfield and Henri Davies" },
  { file: "image753", title: "Louis de Araujo" },
  { file: "image795", title: "Louis de Araujo" },
  { file: "image103", title: "Henri Davies in Valldemossa, Mallorca" },
  { file: "image419-2", title: "Louis de Araujo in Valldemossa, Mallorca" },
  { file: "image626-2", title: "Henri Davies" },
  { file: "image656", title: "Louis de Araujo and Jamie at Cala Deia, Mallorca" },
  { file: "image1036", title: "Louis de Araujo" },
  { file: "image169", title: "Louis de Araujo" },
  { file: "image654", title: "Louis de Araujo, Food market, Palma, Mallorca" },
  { file: "image1116", title: "Louis de Araujo in Palma Cathedral, Palma, Mallorca" },
  { file: "image149", title: "Boarding Tyger yacht, Palma, Mallorca" },
  { file: "image381", title: "Brian Haddock, Sydney" },
  { file: "image771", title: "Barrie Hdfield and Henry Davies, Marseille, France" },
  { file: "image1125", title: "Alfie and Barrie Hadfield at Walthamstow Marshes" },
  { file: "image470", title: "Sally Fisher and Steven Roche" },
  { file: "image251", title: "The Onion Ring 40th Reunion. Treva Norris, Karen Ward and Patrick Brill" },
  { file: "image239", title: "Gillian and Gillian Lenton" },
  { file: "image156", title: "Andrew Irving, Cheryl Johnson and Mario Rodrigues" },
  { file: "image834", title: "Henry Davies, Garth Gething and Rowan" },
  { file: "image49", title: "Gillian Lenton and Karen Hollister" },
  { file: "image454", title: "Steven Roche" },
  { file: "image962", title: "Michael Hunter Smith" },
  { file: "image276", title: "Michael Hunter Smith" },
  { file: "image34", title: "Martie Malan and Michael Hunter Smith" },
  { file: "image1144", title: "Michael Hunter Smith" },
  { file: "image155", title: "Michael Hunter Smith" },
  { file: "image1195", title: "Adi Coetzee" },
  { file: "image735-2", title: "Adi Coetzee and Caroline" },
  { file: "image713", title: "Neil Dundas in Vietnam" },
  { file: "image128", title: "Stephane, Leonardo and Arthur" },
  { file: "image432", title: "Jackie Bryant and Sally Fisher" },
  { file: "image639", title: "Michael van Rensburg" },
  { file: "image399-2", title: "Kevin MacInnes" },
  { file: "image556", title: "Steven Roche" },
  { file: "image117", title: "Steven Roche" },
  { file: "image660", title: "Steven Roche" },
];

export const GALLERIES = {
  "the-stardust": THE_STARDUST,
  "the-boudoir": THE_BOUDOIR,
  "steven": STEVEN,
  "70s": SEVENTIES,
  "80s": EIGHTIES,
  "90s": NINETIES,
  "2000": TWOTHOUSANDS,
};
