/**
 * Content for the Stardust & Beyond site - a 1970s disco photo archive.
 * Extracted from source/Stardust and Beyond/StardustandBeyond.html
 * (a Google-Docs export). Regenerate images with `npm run optimize`,
 * pages with `npm run build`.
 *
 * Each gallery item is { file, title? } - `title` is the photo caption.
 * Array order = display order.
 */

export const SITE = {
  name: "Stardust & Beyond",
  role: "A 1970s disco, and the friends who lived it",
  url: "https://stardustandbeyond.com",
};

export const SOCIAL = {
  instagram: "",
  bluesky: "",
};

// The club photo that leads the site (from the "The Stardust" section).
export const LEAD = { kind: "the-stardust", file: "image472" };

// Section registry - drives the nav, the home "rooms" grid, and page builders.
export const SECTIONS = [
  { kind: "the-stardust", label: "The Stardust", href: "the-stardust.html", unit: "photos", blurb: "The club, 1975." },
  { kind: "the-boudoir", label: "The Boudoir", href: "the-boudoir.html", unit: "photos", blurb: "Steven's back-room, and The Onion Ring." },
  { kind: "steven", label: "Steven", href: "steven.html", unit: "photos", blurb: "Steven Roche, aka Margot." },
  { kind: "70s", label: "70's", href: "70s.html", unit: "photos", blurb: "The decade it all began." },
  { kind: "80s", label: "80's", href: "80s.html", unit: "photos", blurb: "Bigger, brighter, bolder." },
  { kind: "90s", label: "90's", href: "90s.html", unit: "photos", blurb: "The friends, years on." },
];

export const BOUDOIR_TEXT = [
  "The boudoir was the name given to Steven Roche’s bedroom. It was an annex at the back of the Roche family home where a group of very close knit friends used to congregate and hang out all the time. This group was eventually nicknamed The Onion Ring. We used to turn up at the Roche home where the doors were always open and walk through the house greeting other members of the family until we got to Steven’s boudoir where we would spend hours sitting around chatting and drinking endless cups of tea. Occasionally these gatherings would turn into little parties with hysterical laughter and lots of fun and games."
];

export const THE_STARDUST = [
  { file: "image61", title: "Steven Roche aka Margot" },
  { file: "image119", title: "Alan Horn, Patrick Brill and Cindy West" },
  { file: "image211", title: "Cindy West" },
  { file: "image71" },
  { file: "image146", title: "An invitation to the Miss Sunshine at The Butterworth Hotel in Durban" },
  { file: "image79", title: "Rodney Symes, Eric Reeves, Carol and Barry. Eric and Barry were the owners of The Stardust." },
  { file: "image45", title: "Steven at Rocky Horror party" },
  { file: "image196" },
  { file: "image432", title: "Miss Stardust 1977" },
  { file: "image20", title: "Lesley Wallace" },
  { file: "image350" },
  { file: "image125", title: "Gary" },
  { file: "image416", title: "Steven doing cabaret at The Stardust" },
  { file: "image188", title: "Darryl Rogers" },
  { file: "image526", title: "Darryl and Gillian" },
  { file: "image366", title: "Henry Davies and Darryl" },
  { file: "image379", title: "Joan Dickman and Pam Harmse" },
  { file: "image140", title: "Darryl, Kevin Rogers and Gillian Lenton" },
  { file: "image185", title: "Dickie Conradie" },
  { file: "image527", title: "Rene Kent" },
  { file: "image235", title: "Sophie Symes" },
  { file: "image32", title: "Gavin Woolf aka The Weep" },
  { file: "image314", title: "Steven and Craig Peetz" },
  { file: "image68", title: "Steven crowning Miss Stardust 1977" },
  { file: "image44", title: "Steven, Craig, Ronnie Botha, Henry and Mark Griffin" },
  { file: "image194", title: "Henry and Lauren Shipton" },
  { file: "image497", title: "Lauren and Ian Perry" },
  { file: "image14", title: "Craig as Miss Natal 1977" },
  { file: "image523", title: "Kerry Bennett at The Stardust" },
  { file: "image452", title: "Lauren" },
  { file: "image481", title: "Ian Perry winning Miss South Africa" },
  { file: "image233", title: "Miss South Africa Lesley Wallace, Ian Perry, Steven Roche, Gillian and Peter Wheeler The Stardust DJ." },
  { file: "image78" },
  { file: "image384", title: "Steven doing Martie the Martian" },
  { file: "image97", title: "Lauren" },
  { file: "image443", title: "Marcel Wishura" },
  { file: "image275", title: "Ian and Peter Pienaar, the owner of the Stardust" },
];

export const THE_BOUDOIR = [
  { file: "image299", title: "Keith, Trevor Norris, Mark Griffin and Henry Davies" },
  { file: "image422", title: "Steven, Keith, Trevor, Henry, Mark, Michael Hunter Smith, Jackie Bryant, Rodney Symes, Patrick Brill, Steven Kent and Karen Ward" },
  { file: "image2", title: "Steven" },
  { file: "image149", title: "Jackie, Mark & Steven" },
  { file: "image85", title: "Sally Fisher and Steven" },
  { file: "image19", title: "Steven dressed up to crown Miss Stardust 1977" },
  { file: "image377", title: "Henry sewing Steven's dress" },
  { file: "image475", title: "Henry at Steven's birthday party" },
  { file: "image380", title: "Jackie, Henry, Pam, Steven and Conrad" },
  { file: "image92", title: "Jackie, Mrs Roche and Steven aka Rene" },
  { file: "image215", title: "Richard Rufus Ellis and Steven" },
  { file: "image187", title: "Steven and Mark" },
  { file: "image118", title: "Thelma, Mr Roche and Gillian" },
  { file: "image109", title: "Gillian" },
  { file: "image5", title: "Gillian" },
  { file: "image143", title: "Keith and Steven" },
  { file: "image487", title: "Henry" },
  { file: "image302", title: "Gavin, Illana Woolf and Henry" },
  { file: "image27", title: "Steven and Henry" },
];

export const STEVEN = [
  { file: "image450", title: "Steven" },
  { file: "image153", title: "Steven and Jackie" },
  { file: "image72", title: "Steven and Mark" },
  { file: "image248", title: "Steven and Adee" },
  { file: "image332", title: "Steven and Mark" },
  { file: "image100", title: "Steven modelling in Overport City photographed by his father" },
  { file: "image469" },
  { file: "image73" },
  { file: "image4" },
  { file: "image134", title: "Peter Moffat and Steven" },
  { file: "image507", title: "Steven in his back garden" },
  { file: "image195", title: "Steven and Rene- The Eclair Sisters" },
  { file: "image106", title: "Steven and Rene" },
  { file: "image447", title: "Adee and Steven" },
  { file: "image22", title: "Steven as Margot" },
  { file: "image112", title: "Steven and Gary" },
  { file: "image236", title: "Trevor and Steven" },
  { file: "image355", title: "The Eclair Sisters- Trish and Trash Eclair" },
  { file: "image232", title: "Steven" },
  { file: "image496", title: "The Eclair Sisters" },
  { file: "image228", title: "Steven" },
  { file: "image392", title: "Steven doing cabaret in Johannesburg" },
  { file: "image340", title: "Steven and Jackie" },
  { file: "image361", title: "Steven doing cabaret" },
];

export const SEVENTIES = [
  { file: "image367", title: "Henry and Cindy shopping in Durban" },
  { file: "image162", title: "Cindy in Johannesburg" },
  { file: "image294", title: "Cindy" },
  { file: "image82" },
  { file: "image181", title: "Henry at The Linger Longer restaurant in Johannesburg" },
  { file: "image358" },
  { file: "image3", title: "Patrick, Kerry and Mario Rodrigues at Raffles in The Maharani Hotel Durban" },
  { file: "image114", title: "Lawrence Potgieter and Cindy in The Hoffman New Yorker, Hillbrow, Johannesburg" },
  { file: "image312" },
  { file: "image501", title: "Illana and Henry at Jan Smuts airport to see Cindy leave for London" },
  { file: "image102", title: "Henry" },
  { file: "image431", title: "Cindy and Henry" },
  { file: "image288", title: "Ronnie Botha at Marchpane Terraces" },
  { file: "image498", title: "Anthony, Cindy, Patrick and Henry at Marchpane Terraces, Yeoville, Johannesburg" },
  { file: "image11", title: "Henry and Cindy at Marchpane Terraces, Yeoville, Johannesburg" },
  { file: "image516", title: "Cindy messing around in The Landrost Hotel, Johannesburg" },
  { file: "image64", title: "Henry in the army at Bourkes Luck" },
  { file: "image399", title: "Henry in the army" },
  { file: "image449", title: "Rory West and Patrick as trainee chefs at The Elangeni Hotel, Durban" },
  { file: "image375", title: "Illana" },
  { file: "image63", title: "Lauren got shot" },
  { file: "image335", title: "Louis de Araujo" },
  { file: "image512", title: "Rory's 21st birthday, London" },
  { file: "image240", title: "Henry and Chin Soon at Rory's 21st birthday" },
  { file: "image250", title: "Susie and Henry" },
  { file: "image404", title: "The Leopard and Cindy" },
  { file: "image15", title: "Rory, London" },
  { file: "image534", title: "Darryl" },
  { file: "image323", title: "Kerry Bennett modelling The Walsh Marais Gallery kaftan" },
  { file: "image440", title: "Henry working at Thats It, Hillbrow, Johannesburg" },
  { file: "image104", title: "Henry" },
  { file: "image96", title: "Lauren and Rocky Farren" },
  { file: "image396", title: "The Leopard, Rory and Henry" },
  { file: "image264" },
  { file: "image456", title: "Darryl" },
  { file: "image98", title: "Rory and Henry, London" },
  { file: "image462" },
  { file: "image90", title: "Simone and Darryl in Ronnie Botha's flat" },
  { file: "image359", title: "Henry hanging out at Ronnie Botha's flat" },
  { file: "image448", title: "Darryl" },
  { file: "image310", title: "Rory" },
  { file: "image115", title: "Cindy" },
  { file: "image107", title: "Louis, Illana and Michael van Rensburg at Jan Smuts airport for Rory's flight to London" },
  { file: "image208", title: "Rory, Illana and Henry at Jan Smuts airport for Rory's farewell to London" },
  { file: "image219", title: "Janet Marchpane" },
  { file: "image289", title: "Cindy" },
  { file: "image122", title: "Cindy and Henry" },
  { file: "image290", title: "Rory getting ready for New Years Eve party London" },
  { file: "image186", title: "Cindy and Rory" },
  { file: "image43", title: "Rory and Cindy" },
  { file: "image282", title: "Louis' brilliant cartoon" },
  { file: "image313", title: "Louis and Illana seeing Rory off to London" },
  { file: "image435", title: "Marcel Wishura" },
  { file: "image444", title: "Rory in the army In Potschefstroom" },
  { file: "image308", title: "Louis's Christmas Card" },
  { file: "image168", title: "Rene as Miss Subway" },
  { file: "image477", title: "Neil Starr" },
  { file: "image253", title: "Mathew Kelly" },
  { file: "image504", title: "Spencer Pillay and Rene" },
  { file: "image39", title: "Noel van Wildenrath and Henry" },
  { file: "image241", title: "Noel van Wildenrath" },
  { file: "image343", title: "Peter Moffat aka Petal" },
  { file: "image383", title: "Louis' Cartoon" },
  { file: "image175", title: "Darryl" },
  { file: "image229", title: "Steven in Greece" },
  { file: "image400", title: "Steven" },
  { file: "image265", title: "Kerry" },
  { file: "image111", title: "Janet Doby and Patrick" },
  { file: "image145", title: "Patrick and Kerry" },
  { file: "image531", title: "Cindy on holiday" },
  { file: "image368", title: "Cindy and Henry" },
  { file: "image262", title: "The Together Bar, Hillbrow, Johannesburg" },
  { file: "image179", title: "Albie, Stephen Pritchard, Wally Haywood, Bernard Hatch and Henry getting ready for a Rocky Horror party" },
  { file: "image427", title: "Cindy" },
  { file: "image178", title: "Lauren Shipton" },
  { file: "image42", title: "Henry in Paris" },
  { file: "image293", title: "Patrick at The Landdrost Hotel, Johannesburg" },
  { file: "image234", title: "Henry and Illana at her school dance" },
  { file: "image84", title: "Patrick at Chelsea Studios, Chelsea, London" },
  { file: "image470", title: "Henry in London" },
  { file: "image274", title: "Henri and Patrick at he Cinzano Design Competition" },
  { file: "image191", title: "Cheryl Johnson, Sharon Coetsee, Louis, Henry, Stephen and Kerry" },
];

export const EIGHTIES = [
  { file: "image223", title: "Henri, Alan Morrison" },
  { file: "image110", title: "David Goudge" },
  { file: "image48", title: "David, Kerry, Patrick and Henri" },
  { file: "image138", title: "Kevin Botha, Graham Moore, Steven and Peter Moffat" },
  { file: "image473", title: "Cheryl Johnson, David Davies and Henri modelling Andrew Verster's costumes for A Midsummer Night's Dream" },
  { file: "image243", title: "Rehearsal for a show. Steven Lawrences, Dale Shultz, Gary Halfpenny, Kerry, Henri, Gail Butler and Laurel" },
  { file: "image130", title: "Henri Davies" },
  { file: "image304", title: "Steven and Chi Chi La Rue in LA" },
  { file: "image455", title: "Patrick and Henri at Houghton Mansions, Johannesburg" },
  { file: "image193", title: "Louis, Henri and Sophie" },
  { file: "image430", title: "Garth weekend down the South Coast" },
  { file: "image321", title: "Stephen down the South Coast" },
  { file: "image224", title: "Stephen" },
  { file: "image129", title: "Garth" },
  { file: "image457", title: "Mark, Steven and Tom. A weekend at Granny's Cottage, Ballito Bay" },
  { file: "image295", title: "Patrick, Tom, Rene, Steven, Ian Mark & Garth" },
  { file: "image374", title: "Henri, Richard, Ian, Rene, Steven and Ricky" },
  { file: "image465", title: "Ian, Steven, Ricky, Richard, Rene & Henri" },
  { file: "image517", title: "Rene" },
  { file: "image137", title: "Steven and Rene" },
  { file: "image249", title: "Rene" },
  { file: "image16", title: "Rene doing Miss Subway" },
  { file: "image91", title: "x and Rene" },
  { file: "image463", title: "Richard and Tom" },
  { file: "image24", title: "Ian, Richard, Steven and Patrick" },
  { file: "image51", title: "Steven aka The Pennay, Mark and Mathew at the GAZA Ball, Johannesburg" },
  { file: "image244", title: "x, Alan Froneman and Louis- GAZA Ball" },
  { file: "image529", title: "x and Mark" },
  { file: "image25", title: "Henri, The Pennay and Patrick at The Gasa Ball" },
  { file: "image1", title: "Alan aka Alice and Mathew" },
  { file: "image297", title: "Steven, Mark and Mathew" },
  { file: "image238", title: "Mark" },
  { file: "image408", title: "David" },
  { file: "image460", title: "David" },
  { file: "image49", title: "Garth" },
  { file: "image478", title: "Henri and Miguel at Karen Hollister's 21st Birthday" },
  { file: "image307", title: "Rene and Henri" },
  { file: "image105", title: "Alfie Saville and Henri at HD Menswear store, Salisbury Arcade, Durban" },
  { file: "image160", title: "Mirco Broggian at HD Menswear" },
  { file: "image239", title: "Garth and Tamar Marqaud" },
  { file: "image38", title: "Henri, Lianne Basson, Marcel Wishura and Linda Basson. A weekend in the Berg" },
  { file: "image163", title: "Patrick, Henri, Linda and Marcel" },
  { file: "image81", title: "Adele Shandel" },
  { file: "image364", title: "Kerry Bennett Fashion Show Liz Staniford, Cheryl Johhnson & Kerry Bennett" },
  { file: "image402", title: "David Goudge" },
  { file: "image428", title: "A day at Salt Rock Beach Steven and Ian" },
  { file: "image251", title: "Patrick" },
  { file: "image352", title: "Henri and Rene" },
  { file: "image157", title: "Duncan and Liz Good" },
  { file: "image37", title: "Ian, Henri and Patrick" },
  { file: "image480", title: "Rene" },
  { file: "image242", title: "Patrick in Cape Town" },
  { file: "image334", title: "Murray Scannell and Patrick" },
  { file: "image360", title: "Cape Town drag party Lynton Lefevre, Patrick and Maxi Spazzoli" },
  { file: "image206", title: "A weekend down the South Coast Mark Dingley, Henri, Wayne Kobusch and Noel Osborne" },
  { file: "image116", title: "Cape Town road trip Henri, Gary Halfpenny and Mark" },
  { file: "image524", title: "Mark, Gary and Henri" },
  { file: "image286", title: "Medieval Dinner Party, Albion Road, Rondebosch, Cape Town Patrick, Maxi and Henri" },
  { file: "image454", title: "Murray, Jeneanne, Henri, Ian Swan, Maxi, Patrick and Myra" },
  { file: "image52" },
  { file: "image467", title: "Adele's 21st birthday, Cape Town. Stephen, Adele, Henri, Carolyn and Patrick" },
  { file: "image347", title: "Jenny Bear, Carolyn, Marcel and Adele" },
  { file: "image474", title: "Cheryl Schultz" },
  { file: "image280", title: "Cheryl in Miss Scope, Sun City" },
  { file: "image438", title: "Cheryl and Patrick in Le Chic, Durban" },
  { file: "image419", title: "Garth and Patrick" },
  { file: "image205", title: "Patrick, Cheryl and Henri" },
  { file: "image141", title: "David" },
  { file: "image336", title: "Patrick and Garth" },
  { file: "image257", title: "Lauren and Grace Jones" },
  { file: "image515", title: "x, Spencer, Rene and Lauren" },
  { file: "image198", title: "Mark's birthday at Le Chic" },
  { file: "image331", title: "Karen Ward and Steven" },
  { file: "image41", title: "Patrick, Maxi, Kerry, x and Garth" },
  { file: "image326", title: "Kerry" },
  { file: "image521", title: "David, Kerry Patrick and Henri" },
  { file: "image139", title: "Patrick" },
  { file: "image167", title: "Christmas at Ians. Ian" },
  { file: "image277", title: "Stephen" },
  { file: "image337", title: "Rene" },
  { file: "image23", title: "Gillian, Mark and Rene" },
  { file: "image209", title: "Steven" },
  { file: "image509", title: "Gillian and Stephen" },
  { file: "image94", title: "Garth" },
  { file: "image315", title: "Musgrave Mansions, Musgrave Road, Berea, Durban" },
  { file: "image203", title: "Henry at Musgrave Mansions" },
  { file: "image407", title: "Ronnyz" },
  { file: "image426", title: "Kerry, Henry, Maxi and Patrick" },
  { file: "image500", title: "Neville Ward's 50's party Henri, Barbara Lindsey, Kerry, Maxi and Patrick" },
  { file: "image354", title: "Alexander Manbsions, Essenwood Road, Berea, Durban" },
  { file: "image306", title: "Henri's dining room with Casper at Alexander Mansions" },
  { file: "image303", title: "Henri's 30th birthday party, Alexander Mansions, Durban Leigh Downing, Henri, Rene and Kerry" },
  { file: "image348", title: "Steven, Henri and Mark" },
  { file: "image270", title: "Gary, Henri, Mark and Garth" },
  { file: "image7", title: "Peter, Glenda, Rene, Leigh and Steven" },
  { file: "image164", title: "330 Nightclub, Point Road, Durban" },
  { file: "image113", title: "Penny Rey, Sandra and Terry Scott" },
  { file: "image30", title: "Art Deco relaunch Elsa Pretorius, Eddy de Lima, Henri, Leigh, Cecil Sagorin and x" },
  { file: "image124", title: "LA" },
  { file: "image31", title: "Lauren, Jeffery Sanker and x" },
  { file: "image489", title: "x, Lauren and Steven, LA" },
  { file: "image329", title: "Henri's birthday dinner. Sally, Lauren and Steven" },
  { file: "image276", title: "Ian, Henri and Patrick" },
  { file: "image436", title: "Henri and Ian" },
  { file: "image327", title: "Lauren and Patrick" },
  { file: "image420", title: "Duncan and Liz Good's wedding" },
  { file: "image133", title: "Vetchies Pier, Durban Garth and Noel" },
  { file: "image532", title: "David and Bernard" },
  { file: "image485", title: "Jack's farewell drag party. Mark and Patrick" },
  { file: "image378", title: "Henri, Steven, Garth and Mark" },
  { file: "image148", title: "Henri's fashion label launch" },
  { file: "image381", title: "Lauren and Steven" },
  { file: "image342", title: "Michael, Trevor and Steven" },
  { file: "image403", title: "Michael, Trevor and Steven" },
  { file: "image410", title: "Gillian wearing Henri Davies" },
  { file: "image482", title: "Gillian wearing Henri Davies" },
  { file: "image127", title: "Ian in the Glamorous Granny competition" },
  { file: "image29", title: "Peter White in Glamorous Granny" },
  { file: "image339", title: "Ian the winner of Glamorous Granny" },
  { file: "image103", title: "Steven, Neil and x" },
  { file: "image56", title: "Mark" },
  { file: "image513", title: "x, Neil Dundas and Steven" },
  { file: "image200", title: "Lauren and Ian" },
  { file: "image309", title: "Gillian, Lee Fine and Ian" },
  { file: "image183" },
  { file: "image151", title: "Spencer" },
  { file: "image459", title: "Rene" },
  { file: "image356", title: "x and Neil Starr" },
  { file: "image212", title: "Mark" },
  { file: "image510", title: "Rene" },
  { file: "image217", title: "Mark" },
  { file: "image70", title: "Mark" },
  { file: "image159", title: "Mark" },
  { file: "image278", title: "Mark and Lauren in LA" },
  { file: "image458", title: "x, Mark and Lauren" },
  { file: "image322", title: "Lauren" },
  { file: "image170", title: "Mark in LA" },
  { file: "image214", title: "Mark" },
  { file: "image59", title: "Mark and Herb Klein" },
  { file: "image273", title: "Mark and Herb Klein" },
  { file: "image197", title: "Louis and Sophie" },
  { file: "image525", title: "Mathew" },
  { file: "image62", title: "Mark" },
  { file: "image99", title: "Mathew" },
  { file: "image471", title: "Steven, Michael and Arthur" },
  { file: "image413", title: "Rene as Miss Subway" },
  { file: "image281", title: "Mark" },
  { file: "image245", title: "Gillian" },
  { file: "image54", title: "Trevor, Steven and Neil" },
  { file: "image6", title: "Seaton, Mark and Spencer" },
  { file: "image204", title: "Peter and The Pennay" },
  { file: "image89", title: "x and Mark" },
  { file: "image409", title: "Mark" },
  { file: "image263", title: "Mark" },
  { file: "image508", title: "Mark" },
  { file: "image230", title: "Mark" },
  { file: "image284", title: "Mark and The Weep" },
  { file: "image142", title: "Seaton and Mark" },
  { file: "image311", title: "Mark, x and Spencer" },
  { file: "image391", title: "x, Gillian and Mark" },
  { file: "image21", title: "Mark" },
  { file: "image227", title: "Mark, Gillian and Seaton" },
  { file: "image136", title: "Liz Staniford and Andries Botha's wedding invite" },
  { file: "image246", title: "Patrick and model" },
  { file: "image218", title: "Noel Osborne, Stephen, Patrick Henri, Derek Lavarack and Alan Watt" },
  { file: "image296", title: "Stephen and Bernard" },
  { file: "image189", title: "Neil Starr and Henri" },
  { file: "image95", title: "Rene, Peter and Steven" },
  { file: "image370", title: "Gavin and Jackie" },
  { file: "image320", title: "Noel von Wildenrath and Rene" },
  { file: "image305", title: "Mark" },
  { file: "image161", title: "Patrick, Christine Popoff, Anina Cummings, Mark and Kerry" },
  { file: "image154", title: "Patrick, Mark and Arthur" },
  { file: "image60", title: "Thelma and Tony" },
  { file: "image503", title: "A night at The Zodiac nightclub. Alex Botha, Linda Basson, Marcel Wishura, Lianne Basson, Henri and Kerry" },
  { file: "image492", title: "Eddie de Lima and Tanya van Agthoven" },
  { file: "image414", title: "Sally" },
  { file: "image150", title: "Mathew" },
  { file: "image202", title: "Tanya van Agthoven and Leigh Downing" },
  { file: "image86", title: "Mark, Jackie and Spencer" },
  { file: "image319", title: "Mark" },
  { file: "image453", title: "Jackie" },
  { file: "image207", title: "Mark" },
  { file: "image177", title: "Venice Road cottage" },
  { file: "image10", title: "Louis" },
  { file: "image34", title: "Patrick, Louis and Henri" },
  { file: "image220", title: "Henri" },
  { file: "image271", title: "Steven" },
  { file: "image388", title: "Steven" },
  { file: "image324", title: "Garth and Patrick" },
  { file: "image269", title: "Louis" },
  { file: "image362", title: "Steven at Derek Meuvis's pool" },
  { file: "image382", title: "Rene's invite" },
  { file: "image464", title: "Steven" },
  { file: "image292", title: "Best Dressed Men" },
  { file: "image55", title: "Louis Christmas Card" },
  { file: "image385", title: "Lauren modelling in LA" },
  { file: "image121", title: "Mark and Steven in Amanzimtoti" },
];

export const NINETIES = [
  { file: "image349", title: "Garth and Henri in Durban" },
  { file: "image35", title: "Joan and her son at her graduation" },
  { file: "image93", title: "Garth and Henri" },
  { file: "image169", title: "Louis and Jessie in Vancouver, Canada" },
  { file: "image182", title: "Colin Mc Gree and Patrick" },
  { file: "image199", title: "Mark Lowe" },
  { file: "image231", title: "Michael, Patrick and Rene" },
  { file: "image222", title: "Seaton and Arthur" },
  { file: "image328", title: "Arthur and Stefan" },
  { file: "image138", title: "Kevin Mac Innes, Graham Moore, Steven and Peter" },
  { file: "image174", title: "Steven and Jackie" },
  { file: "image50", title: "Seaton" },
  { file: "image272", title: "Seaton and Steven" },
  { file: "image446", title: "Steven, Henri and Garth at Garth's party in Durban" },
  { file: "image301", title: "Garth, Gary Searle, Garth Marquard and Boyd Ferguson" },
  { file: "image316", title: "David Ralphs, Peter Wishart and Alfie Bosman" },
  { file: "image330", title: "Henri and Steven" },
  { file: "image363", title: "Henri and Steven" },
  { file: "image47", title: "Michael and Steven" },
  { file: "image506", title: "Steven, Michael and Steven's work colleagues" },
  { file: "image135", title: "Ian and Gillian" },
  { file: "image258", title: "Steven" },
  { file: "image173", title: "Steven's favourite cafe at Mitchell Park, Durban" },
  { file: "image254", title: "Priscilla Blackie, Penny Brill, Nicola and Megan Blackie, Steven" },
  { file: "image357", title: "Patrick, Johan, Steven, Trevor and Gavin" },
  { file: "image252", title: "Lauren, Henri and Patrick" },
  { file: "image287", title: "Steven and Colin Hutt" },
  { file: "image33", title: "Patrick, Steven, Sally and Michael" },
  { file: "image491", title: "Michael, Patrick, Steven and Kevin MacInnes" },
  { file: "image210", title: "Sally and Steven" },
  { file: "image486", title: "Karen Ward and Richard" },
  { file: "image393", title: "330 Party Mark, Sally Chance, Patrick, Carrie and Carl Isaacs" },
  { file: "image256", title: "Mark, Carrie, Carmen Laurier, and Rafe Brown" },
  { file: "image494", title: "Jenna, Michael and Seaton" },
  { file: "image17", title: "Henri and Barrie in Canterbury" },
  { file: "image285", title: "Rocky Horror Party Patrick, Steven and Kevin Mc Innes" },
  { file: "image65", title: "Michael, Steven and Patrick" },
  { file: "image101", title: "Karen, Steven and Lisa" },
  { file: "image87", title: "Steven and Arthur" },
  { file: "image317", title: "Trevor and Steven" },
  { file: "image298", title: "Steven" },
  { file: "image76", title: "Leigh, Heather Roche, Steven and Karen" },
  { file: "image132", title: "Allen and Steven" },
  { file: "image279", title: "Brettlee, Michael and Kevin" },
  { file: "image255", title: "Steven and Patrick" },
  { file: "image12", title: "Carolyn de Beyer, Shaun" },
  { file: "image126", title: "Steven" },
  { file: "image488", title: "Cheryl and Robert Johnson" },
  { file: "image369", title: "Colin Hutt" },
  { file: "image437", title: "Steven and Peter" },
  { file: "image466", title: "Steven and colleagues" },
  { file: "image144", title: "Steven, Sally, Patrick and Michael" },
  { file: "image344", title: "Aydee and Gillian" },
  { file: "image261", title: "Gillian and Lisa Owen" },
  { file: "image505", title: "Neil and Gillian" },
  { file: "image180", title: "Karen, Gillian and Lisa" },
  { file: "image201", title: "Gillian, Neil and Spencer" },
  { file: "image152", title: "Michael" },
  { file: "image479", title: "Henri and Lauren, LA, California" },
  { file: "image83", title: "Lauren and Peter Amsden, Laurel Canyon, LA" },
  { file: "image401", title: "Michael" },
  { file: "image26", title: "Michael" },
  { file: "image490", title: "Michael and Patrick" },
  { file: "image260", title: "Neil, Sally, Patrick and Michael" },
  { file: "image445", title: "Steven, Michael, Kevin McInnes and Patrick" },
  { file: "image522", title: "Colin, Douglas, Michael, Sally, Bretlee, Seaton, Patrick and Steven at The Trossachs, MacGregor" },
  { file: "image441", title: "Michael and Seaton" },
  { file: "image418", title: "Michael" },
  { file: "image128", title: "Spencer, Seaton and Steven" },
  { file: "image57", title: "Joan, Seaton, Patrick and Brettlee" },
  { file: "image266", title: "Patrick, Brettlee, Neil, Michael and Sally" },
  { file: "image213", title: "Steven and Michael" },
  { file: "image417" },
  { file: "image386", title: "Michael and Seaton" },
  { file: "image433", title: "Douglas" },
  { file: "image9", title: "Lisa, Karen, Sally, Lee and Glenda" },
  { file: "image518", title: "Petal and The Pennay" },
  { file: "image320", title: "Noel and Rene" },
  { file: "image117", title: "Noel" },
  { file: "image421", title: "Patrick and Henri at St Margaret's Bay, England" },
  { file: "image158", title: "Patrick and Michael" },
  { file: "image53", title: "Patrick and Sally" },
  { file: "image345", title: "Steven and Patrick" },
  { file: "image190", title: "Patrick and Dada" },
  { file: "image131", title: "Luke Davies, Henri, Neil Farrelly and Barrie Hadfield in London" },
  { file: "image108", title: "Luke, Peter White, Henri and Barrie" },
  { file: "image372", title: "Greg Davies, Henri, Peter and Luke in The Fridge, Brixton London" },
  { file: "image259", title: "Barrie and Henri in The Fridge, Brixton, London" },
  { file: "image66", title: "Patrick, Kerry and Neville Ward" },
  { file: "image225", title: "Henri, Luke and Barrie. Christmas in West Hampstead, London" },
  { file: "image18", title: "Oliver Ellis and Henri at Gay Pride 94 in London" },
  { file: "image405", title: "Henri and Jonathan Arun at Gay Pride" },
  { file: "image495", title: "Patrick, Kevin and Michael" },
  { file: "image318", title: "Patrick" },
  { file: "image171", title: "The Dead Sea, Israel" },
  { file: "image520", title: "Henri in the Dead Sea" },
  { file: "image502", title: "Henri" },
  { file: "image120", title: "Barrie" },
  { file: "image371", title: "Barrie, Shlommie and Henri at En Gedi, The Dead Sea, Israel" },
  { file: "image216", title: "Barrie" },
  { file: "image13", title: "Henri on the Bishop's throne, The Church of the Holy Sepulchre, Jerusalem, Israel" },
  { file: "image423", title: "Rene and Karen" },
  { file: "image221", title: "Sally, Steven and Richard" },
  { file: "image338", title: "Henri and Garth, Spitalfields, London" },
  { file: "image394", title: "Luke and Barrie" },
  { file: "image533", title: "Peter Wishart and Garth, Spitalfields, London" },
  { file: "image365", title: "Peter" },
  { file: "image484", title: "Garth and Rafe Brown, Spitalfields, London" },
  { file: "image406", title: "Luke and Henri" },
  { file: "image192", title: "Barrie and Henri" },
  { file: "image434", title: "Onion Ring 20th year reunion. Trevor, Ian, Aydee, Peter, Sally, Mrs Roche, Joan, Pam and Karen" },
  { file: "image530", title: "Jenna and Seaton" },
  { file: "image325", title: "Sean Keegan and Peter" },
  { file: "image165", title: "Shaun, Carolyn and Micheal Cheze" },
  { file: "image75", title: "Kevin, Patrick and Steven" },
  { file: "image28", title: "Steven and Colin" },
  { file: "image74", title: "Seaton, Michael and Rene" },
  { file: "image341", title: "Steven" },
  { file: "image176", title: "Garth and Todd Barry. Spitalfields, London" },
  { file: "image442", title: "Steven" },
  { file: "image156", title: "Kevin and Steven" },
  { file: "image8", title: "Steven" },
  { file: "image425", title: "Steven and Frank Melman" },
  { file: "image424", title: "Henri and Mark Davis in the DJ booth of Heaven, London" },
  { file: "image123", title: "Mark Davis" },
  { file: "image499", title: "Henri at Mark's flat, Battersea, London" },
  { file: "image397", title: "Steven" },
  { file: "image493", title: "Henri- Trade membership card" },
  { file: "image333", title: "James Moffat and Henri, Spitalfields, London" },
  { file: "image351", title: "James, Barrie and Henri" },
  { file: "image346", title: "Steven" },
  { file: "image412", title: "Steven" },
  { file: "image268", title: "Henri and Mark Cioli, England" },
  { file: "image40", title: "Steven" },
  { file: "image155", title: "Henri in Cheshire" },
  { file: "image390", title: "Cheryl and Patrick" },
  { file: "image376", title: "Sally and Jenna" },
  { file: "image389", title: "Steven and Patrick" },
  { file: "image353", title: "Arthur, Neil and Michael" },
  { file: "image226", title: "Patrick and Steven" },
  { file: "image373", title: "Alan Whitehead and Colin" },
  { file: "image166", title: "Steven and Garth" },
  { file: "image468", title: "Leigh and Duncan" },
  { file: "image283", title: "Jackie" },
  { file: "image147", title: "Jackie and Sally" },
  { file: "image77", title: "Josef, Aydee and Neil" },
  { file: "image387", title: "Neil and Michael" },
  { file: "image514", title: "Garth and Henri in Durban" },
  { file: "image395", title: "Peter White's Mother NYE Party" },
  { file: "image439", title: "Nicole, Upstate New York" },
  { file: "image461", title: "Henri" },
  { file: "image415", title: "Wayne Lukas" },
  { file: "image184", title: "Henri in Chloe's flat, Egerton Gardens, South Kensington, London" },
  { file: "image46", title: "Henri in New York" },
  { file: "image80", title: "John Truex, New York" },
  { file: "image300", title: "Ian, New York" },
  { file: "image483", title: "Henri, New York" },
  { file: "image88", title: "Gregory Pierrotti, New York" },
  { file: "image247", title: "Henri" },
  { file: "image267", title: "Henri" },
  { file: "image67", title: "Chloe Rolfes and Henri in New York" },
  { file: "image511", title: "Henri working at Kin Khao, New York" },
  { file: "image451", title: "Christine, Henri and Guy, Kin Khao, New York" },
  { file: "image58", title: "Brad" },
  { file: "image398", title: "Henri" },
  { file: "image291", title: "Steven and Patrick" },
  { file: "image172", title: "Henri in Juice, Covent Garden, London" },
  { file: "image528", title: "David Ross" },
  { file: "image411", title: "Juice menu" },
  { file: "image519", title: "Craig" },
  { file: "image237", title: "Barrie and Henri" },
  { file: "image36", title: "First iMac Internet cafe in London" },
  { file: "image476", title: "Juice" },
  { file: "image69", title: "Art Gallery and Internet Cafe at Juice, Covent Garden, London" },
  { file: "image429" },
];

export const GALLERIES = {
  "the-stardust": THE_STARDUST,
  "the-boudoir": THE_BOUDOIR,
  "steven": STEVEN,
  "70s": SEVENTIES,
  "80s": EIGHTIES,
  "90s": NINETIES,
};
